import { test, expect } from '@playwright/test';
import fs from 'node:fs';

const SB='https://lqnnqsopdqnibbyzoakc.supabase.co';
const AUTH=`${SB}/functions/v1/prime-auth`;
const CLEAN=`${SB}/functions/v1/prime-qa-cleanup`;
const RUN=String(process.env.GITHUB_RUN_ID||Date.now());
const VIEWS=[['cardv',/TODAY|LIVE/i],['checkv',/CHECK/i],['calv',/CAL|КАЛЕНДАР/i],['friendsv',/SOCIAL/i]];
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'screen';
const bug=(a,severity,code,title,meaning,detail={})=>a.push({severity,code,title,meaning,detail});

async function authQA(request,project){
  const s=slug(project).replace(/-/g,'').slice(0,12),qa={email:`qa2-${RUN}-${s}@prime.invalid`,password:`PrimeQA-${RUN}-${s}-X9!`,handle:`qa2_${String(RUN).slice(-10)}_${s}`.slice(0,32),display_name:`QA 2.0 ${s}`.slice(0,32)};
  fs.mkdirSync('artifacts',{recursive:true});fs.appendFileSync('artifacts/qa-accounts.ndjson',JSON.stringify({email:qa.email,handle:qa.handle,run_id:RUN,project})+'\n');
  let r=await request.post(AUTH,{data:{action:'signup',...qa}}),d=await r.json().catch(()=>({}));if(r.ok()&&d?.token)return d.token;
  r=await request.post(AUTH,{data:{action:'login',email:qa.email,password:qa.password}});d=await r.json().catch(()=>({}));if(!r.ok()||!d?.token)throw new Error(`QA auth failed ${r.status()} ${JSON.stringify(d).slice(0,300)}`);return d.token;
}
async function cleanupQA(request,token){if(!token)return{ok:false,skipped:true};try{const r=await request.post(CLEAN,{headers:{Authorization:`Bearer ${token}`},data:{}});return{ok:r.ok(),status:r.status(),body:await r.json().catch(()=>({}))}}catch(e){return{ok:false,error:String(e).slice(0,300)}}}

async function dismiss(page){
  for(let pass=0;pass<2;pass++)for(const s of ['#releasecontinue','.prime-guide-skip','[data-prime-guide="skip"]','[data-action="onboard-skip"]','button:has-text("ПРОПУСТИТЬ")','button:has-text("Пропустить")','button:has-text("ВОЙТИ В PRIME")']){const e=page.locator(s).first();if(await e.isVisible().catch(()=>false)){await e.click({timeout:1800}).catch(()=>null);await page.waitForTimeout(220)}}
}

async function dom(page){return page.evaluate(()=>{
  const vis=e=>{if(!e)return false;const c=getComputedStyle(e),r=e.getBoundingClientRect();return c.display!=='none'&&c.visibility!=='hidden'&&Number(c.opacity||1)>.02&&r.width>0&&r.height>0};
  const name=e=>(e?.getAttribute?.('aria-label')||e?.textContent||e?.id||e?.tagName||'').trim().replace(/\s+/g,' ').slice(0,110),vw=innerWidth,vh=innerHeight;
  const gate=document.getElementById('primecallpermissiongate'),gateOn=vis(gate),overlays=['sheetback','releasegate','onboard','avatarviewer'].map(id=>document.getElementById(id)).filter(vis),root=overlays[0]||document;
  const offscreen=[],covered=[],gateBlocked=[],overflowElements=[];
  const scrollParent=e=>{let p=e.parentElement;while(p&&p!==document.body){const c=getComputedStyle(p);if(/(auto|scroll)/.test(`${c.overflowX} ${c.overflowY}`))return true;p=p.parentElement}return false};
  for(const e of [...root.querySelectorAll('button,a[href],input,textarea,select,[role="button"]')].filter(vis).slice(0,220)){
    if(e.disabled||e.getAttribute('aria-disabled')==='true')continue;const r=e.getBoundingClientRect(),n=name(e);if(!scrollParent(e)&&(r.left<-4||r.right>vw+4))offscreen.push({name:n,left:Math.round(r.left),right:Math.round(r.right),width:Math.round(r.width)});
    if(r.bottom>=0&&r.top<=vh){const x=Math.max(1,Math.min(vw-1,r.left+r.width/2)),y=Math.max(1,Math.min(vh-1,r.top+r.height/2)),top=document.elementFromPoint(x,y);if(top&&!(top===e||e.contains(top)||top.contains(e))){const hit={name:n,coveredBy:name(top),top:Math.round(r.top),bottom:Math.round(r.bottom)};if(gateOn&&gate.contains(top))gateBlocked.push(hit);else covered.push(hit)}}
  }
  for(const e of [...document.querySelectorAll('body *')].filter(vis).slice(0,800)){if(scrollParent(e))continue;const r=e.getBoundingClientRect();if(r.width>vw*2.5)continue;if(r.left<-4||r.right>vw+4)overflowElements.push({name:name(e),tag:e.tagName,id:e.id,cls:String(e.className||'').slice(0,90),left:Math.round(r.left),right:Math.round(r.right),width:Math.round(r.width)})}
  const ox=scrollX,oy=scrollY;window.scrollTo(50,oy);const horizontalScrollable=scrollX>1;window.scrollTo(ox,oy);
  const n=document.querySelector('.prime-navigator-more'),nr=n&&vis(n)?{children:n.children.length,hasMoreCopy:!!n.querySelector('.morecopy'),text:name(n),width:Math.round(n.getBoundingClientRect().width),height:Math.round(n.getBoundingClientRect().height)}:null;
  return{viewport:{w:vw,h:vh},bodyText:(document.body.innerText||'').trim().length,activeViews:[...document.querySelectorAll('#app .view.on')].filter(vis).map(e=>e.id||String(e.className)),overlayCount:overlays.length,overlayIds:overlays.map(e=>e.id),overflow:Math.max(0,document.documentElement.scrollWidth-vw),horizontalScrollable,overflowElements:overflowElements.slice(0,16),offscreen,covered,gateBlocked,callGate:gateOn?{text:name(gate),rect:(()=>{const r=gate.getBoundingClientRect();return{top:Math.round(r.top),bottom:Math.round(r.bottom),left:Math.round(r.left),right:Math.round(r.right),height:Math.round(r.height)}})()}:null,brokenImages:[...document.images].filter(vis).filter(i=>i.complete&&(!i.naturalWidth||!i.naturalHeight)).map(i=>(i.currentSrc||i.src||'').slice(0,180)),loaders:[...document.querySelectorAll('.planloading,.planbuilding,.insightsloading,.pushbusy,[aria-busy="true"]')].filter(vis).map(name),navigatorCard:nr};
})}
async function stable(page,id){await page.waitForTimeout(600);if(id==='checkv'){const t=Date.now();while(Date.now()-t<4200){if(!await page.getByText(/NERVE CONNECTING/i).isVisible().catch(()=>false))break;await page.waitForTimeout(300)}}await dismiss(page)}
async function waitLoad(page,max=4200){const t=Date.now();while(Date.now()-t<max){const a=await dom(page);if(!a.loaders.length)return{stuck:false,loaders:[]};await page.waitForTimeout(280)}const a=await dom(page);return{stuck:!!a.loaders.length,loaders:a.loaders}}
async function nav(page,id,rx){for(const e of [page.locator(`[data-x-view="${id}"]`).first(),page.locator(`[data-v="${id}"]`).first(),page.getByRole('button',{name:rx}).first()])if(await e.isVisible().catch(()=>false))return e;return null}
async function go(page,id,rx,issues){await dismiss(page);const e=await nav(page,id,rx);if(!e){bug(issues,'HIGH','NAV_TAB_MISSING',`${id}: нет навигации`,'Основной экран невозможно открыть через видимую навигацию.');return false}try{await e.click({timeout:3000})}catch(err){bug(issues,'HIGH','NAV_TAP_FAILED',`${id}: тап заблокирован`,'Видимая кнопка навигации не принимает обычный тап.',{error:String(err).slice(0,330)});return false}await stable(page,id);const ok=await page.locator(`#${id}`).first().isVisible().catch(()=>false);if(!ok)bug(issues,'HIGH','NAV_WRONG_TARGET',`${id}: экран не открылся`,'После тапа ожидаемый view не стал видимым.');return ok}

function save(project,r){fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync(`artifacts/autopilot-${project}.json`,JSON.stringify(r,null,2));const c=r.issues.reduce((a,x)=>(a[x.severity]=(a[x.severity]||0)+1,a),{}),o=[`# PRIME QA Autopilot 2.0 — ${project}`,'',`- Run: ${RUN}`,`- Release: ${r.release}`,`- Duration: ${r.duration_ms} ms`,`- Screens: ${r.screens.length}`,`- Issues: ${r.issues.length} (CRITICAL ${c.CRITICAL||0}, HIGH ${c.HIGH||0}, MEDIUM ${c.MEDIUM||0}, LOW ${c.LOW||0})`,`- QA cleanup: ${r.cleanup?.ok?'OK':'FAILED'}`,'','## Bugs',''];if(!r.issues.length)o.push('Подтверждённых проблем не найдено.');r.issues.forEach((x,i)=>o.push(`### BUG-${String(i+1).padStart(3,'0')} · ${x.severity} · ${x.code}`,`**Баг:** ${x.title}`,`**Что это значит:** ${x.meaning}`,`**Детали:** \`${JSON.stringify(x.detail).slice(0,1900)}\``,''));o.push('## Runtime evidence','',`- Page errors: ${r.page_errors.length}`,`- Failed requests: ${r.request_failures.length}`,`- HTTP 4xx: ${r.http_4xx.length}`,`- HTTP 5xx: ${r.http_5xx.length}`,`- Console errors: ${r.console_errors.length}`);fs.writeFileSync(`artifacts/autopilot-${project}.md`,o.join('\n'))}

test('PRIME QA Autopilot 2.0 live production run',async({page,request},info)=>{
  const start=Date.now(),project=info.project.name,issues=[],screens=[],consoleErrors=[],pageErrors=[],requestFailures=[],http4xx=[],http5xx=[];let release='unknown',fatal=null,token=null,cleanup={ok:false,skipped:true};fs.mkdirSync('artifacts/screens',{recursive:true});
  page.on('console',m=>{if(m.type()==='error')consoleErrors.push({text:m.text().slice(0,1000),page:page.url()})});page.on('pageerror',e=>pageErrors.push({message:String(e?.message||e).slice(0,1200)}));page.on('requestfailed',r=>requestFailures.push({method:r.method(),url:r.url().slice(0,600),error:r.failure()?.errorText||'failed'}));page.on('response',r=>{if(r.status()>=500)http5xx.push({status:r.status(),url:r.url().slice(0,600)});else if(r.status()>=400)http4xx.push({status:r.status(),url:r.url().slice(0,600)})});
  const audit=async label=>{await dismiss(page);const ld=await waitLoad(page);if(ld.stuck)bug(issues,'HIGH','STUCK_LOADER',`${label}: loader завис`,'Экран слишком долго остаётся в загрузке.',{loaders:ld.loaders});const a=await dom(page),shot=`artifacts/screens/${slug(project)}-${slug(label)}.png`;await page.screenshot({path:shot,fullPage:false});screens.push({label,screenshot:shot,audit:a});if(a.bodyText<10)bug(issues,'CRITICAL','BLANK_SCREEN',`${label}: пустой экран`,'PRIME не отрисовался.');if(a.overflow>4&&a.horizontalScrollable)bug(issues,'HIGH','HORIZONTAL_SCROLL',`${label}: горизонтальный скролл`,'Страницу можно реально сдвинуть по X.',{overflow:a.overflow,elements:a.overflowElements});if(a.activeViews.length!==1)bug(issues,'HIGH','ACTIVE_VIEW_COUNT',`${label}: active views ${a.activeViews.length}`,'Несколько основных экранов активны одновременно или ни одного.',{activeViews:a.activeViews});if(a.overlayCount>1)bug(issues,'HIGH','MULTIPLE_OVERLAYS',`${label}: ${a.overlayCount} модалки`,'Несколько независимых modal-root одновременно блокируют интерфейс.',{overlayIds:a.overlayIds});if(a.gateBlocked.length)bug(issues,'HIGH','CALL_PERMISSION_GATE_BLOCKS_UI',`${label}: разрешение звонков перекрывает управление`,'Баннер входящих видеозвонков физически лежит поверх других кнопок и забирает их тапы.',{gate:a.callGate,blocked:a.gateBlocked});if(a.covered.length)bug(issues,'HIGH','COVERED_TAP_TARGET',`${label}: кнопка перекрыта`,'Hit-test в центре видимой кнопки попадает в другой слой.',{elements:a.covered});if(a.offscreen.length)bug(issues,'MEDIUM','OFFSCREEN_CONTROLS',`${label}: контролы за экраном`,'Интерактивные элементы выходят за viewport.',{elements:a.offscreen});if(a.brokenImages.length)bug(issues,'MEDIUM','BROKEN_IMAGE',`${label}: битая картинка`,'Изображение не загрузилось.',{images:a.brokenImages});if(a.navigatorCard&&(!a.navigatorCard.hasMoreCopy||a.navigatorCard.children<3))bug(issues,'HIGH','NAVIGATOR_CARD_LAYOUT',`${label}: карточка НАВИГАТОР развалена`,'Её структура не соответствует grid moreitem, поэтому подпись и ? съезжают.',a.navigatorCard);return a};
  try{
    token=await authQA(request,project);await page.addInitScript(t=>{localStorage.setItem('prime_token',t);window.__primeQA={cls:0};try{new PerformanceObserver(l=>{for(const e of l.getEntries())if(!e.hadRecentInput)window.__primeQA.cls+=(e.value||0)}).observe({type:'layout-shift',buffered:true})}catch{}},token);
    const r=await page.goto('/',{waitUntil:'domcontentloaded',timeout:20000});if(!r||r.status()>=500)bug(issues,'CRITICAL','BOOT_HTTP','Production не загрузился','Сервер вернул 5xx до появления UI.',{status:r?.status()});await page.waitForTimeout(1100);await dismiss(page);await expect(page.locator('#app')).toBeVisible();release=await page.evaluate(()=>window.PRIME_RELEASE||'unknown');await audit('boot-live');
    for(const[id,rx]of VIEWS)if(await go(page,id,rx,issues))await audit(id);
    await dismiss(page);let state=await dom(page);if(!state.callGate){const more=page.locator('#moremenu').first();if(await more.isVisible().catch(()=>false)){try{await more.click({timeout:2800});await page.waitForTimeout(320);await audit('more-menu');const back=page.locator('#sheetback');if(await back.isVisible().catch(()=>false)){await back.click({position:{x:2,y:2},timeout:2200}).catch(()=>null);await page.waitForTimeout(400);if(await back.isVisible().catch(()=>false))bug(issues,'MEDIUM','OUTSIDE_TAP_NOT_DISMISSED','Тап по фону не закрыл меню','Sheet остаётся открытым после тапа вне него.')}}catch(e){bug(issues,'HIGH','MORE_MENU_BLOCKED','Меню ••• не открывается','Другой слой перехватывает тап по дополнительному меню.',{error:String(e).slice(0,350)})}}}
    await dismiss(page);for(let i=0;i<20;i++){state=await dom(page);if(state.callGate){bug(issues,'HIGH','STRESS_BLOCKED_BY_CALL_GATE','Stress остановлен баннером звонков','Во время быстрых переходов баннер разрешения перекрыл интерфейс.',{iteration:i,gate:state.callGate});break}const[id,rx]=VIEWS[i%4],e=await nav(page,id,rx);if(!e){bug(issues,'HIGH','STRESS_NAV_MISSING',`Stress: ${id} исчезла`,'После быстрых переходов навигация пропала.',{iteration:i});break}try{await e.click({timeout:2000})}catch(err){bug(issues,'HIGH','STRESS_TAP_FAILED',`Stress: ${id} не нажалась`,'При быстрых переходах тап перестал проходить.',{iteration:i,error:String(err).slice(0,300)});break}await page.waitForTimeout(70)}await page.waitForTimeout(400);await audit('stress-after-20-tabs');const m=await page.evaluate(()=>window.__primeQA||{cls:0});if(Number(m.cls)>.25)bug(issues,'MEDIUM','LAYOUT_SHIFT','Сильный layout shift','UI заметно прыгает без пользовательского действия.',{cls:m.cls});
  }catch(e){fatal=String(e?.stack||e).slice(0,3500);bug(issues,'CRITICAL','AUTOPILOT_FATAL','Прогон оборвался','Ошибка зафиксирована, а не скрыта зависанием.',{error:fatal})}
  finally{
    if(pageErrors.length)bug(issues,'CRITICAL','PAGE_ERRORS',`Page exceptions: ${pageErrors.length}`,'Есть необработанные JavaScript-исключения.',{sample:pageErrors.slice(0,8)});if(requestFailures.length)bug(issues,'MEDIUM','REQUEST_FAILURES',`Failed requests: ${requestFailures.length}`,'Сетевые запросы физически оборвались.',{sample:requestFailures.slice(0,10)});if(http5xx.length)bug(issues,'HIGH','HTTP_5XX',`HTTP 5xx: ${http5xx.length}`,'Backend PRIME вернул серверную ошибку.',{sample:http5xx.slice(0,10)});const h4=http4xx.filter(x=>!x.url.includes('favicon')&&!x.url.includes('/manifest'));if(h4.length)bug(issues,'MEDIUM','HTTP_4XX',`HTTP 4xx: ${h4.length}`,'Обычный пользовательский сценарий вызывает endpoint с клиентской ошибкой.',{sample:h4.slice(0,10)});if(consoleErrors.length)bug(issues,'MEDIUM','CONSOLE_ERRORS',`Console errors: ${consoleErrors.length}`,'Production пишет ошибки в browser console.',{sample:consoleErrors.slice(0,8)});
    cleanup=await cleanupQA(request,token);save(project,{run_id:RUN,project,url:page.url(),release,duration_ms:Date.now()-start,issues,screens,console_errors:consoleErrors,page_errors:pageErrors,request_failures:requestFailures,http_4xx:http4xx,http_5xx:http5xx,fatal,cleanup});
  }
  expect(issues.filter(x=>x.severity==='CRITICAL'||x.severity==='HIGH'),'HIGH/CRITICAL PRIME issues; inspect artifact').toHaveLength(0);
});
