import {test,expect} from '@playwright/test';
const BASE=process.env.PRIME_URL||'https://prime-online-v01.vercel.app/';
const SB='https://lqnnqsopdqnibbyzoakc.supabase.co',AUTH=SB+'/functions/v1/prime-auth',CONNECT=SB+'/functions/v1/prime-connect',CALL=SB+'/functions/v1/prime-call',CLEAN=SB+'/functions/v1/prime-qa-cleanup';
const RUN=String(process.env.GITHUB_RUN_ID||Date.now());
const post=(r,u,t,d)=>r.post(u,{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},data:d,timeout:20000});
async function signup(r,p,s){const tag=(RUN.slice(-8)+s+p.replace(/[^a-z0-9]/gi,'').slice(0,6)).slice(0,18),q={email:`qa4-${tag}@prime.invalid`,password:`PrimeCall4-${tag}-X9!`,handle:`qa4_${tag}`.toLowerCase(),display_name:`QA 4.0 ${s.toUpperCase()} ${p}`.slice(0,32)};const x=await r.post(AUTH,{data:{action:'signup',...q},timeout:15000}),d=await x.json();if(!x.ok()||!d.token)throw new Error('signup '+x.status());return{...q,token:d.token}}
async function pair(r,p){const a=await signup(r,p,'a'),b=await signup(r,p,'b');let x=await post(r,CONNECT,a.token,{action:'create_invite'}),d=await x.json();x=await post(r,CONNECT,b.token,{action:'accept',code:d.code});if(!x.ok())throw new Error('pair '+x.status());return{a,b}}
async function clean(r,q){if(!q)return;for(const x of [q.a,q.b])await r.post(CLEAN,{headers:{Authorization:`Bearer ${x.token}`},data:{},timeout:12000}).catch(()=>{})}
async function pageFor(browser,token,p){const v=p==='compact-iphone'?{width:375,height:667}:{width:393,height:852},c=await browser.newContext({viewport:v,isMobile:true,hasTouch:true,deviceScaleFactor:p==='compact-iphone'?2:3});await c.grantPermissions(['camera','microphone','notifications'],{origin:new URL(BASE).origin}).catch(()=>{});const page=await c.newPage();await page.addInitScript(t=>localStorage.setItem('prime_token',t),token);await page.goto(BASE,{waitUntil:'domcontentloaded',timeout:25000});await page.evaluate(()=>{document.getElementById('releasegate')?.remove();document.getElementById('onboard')?.remove()});await page.waitForFunction(()=>window.PRIME_R1114_VIDEO_CALL&&window.PRIME?.state?.mine,null,{timeout:18000});return{c,page}}
async function start(page,h){await page.evaluate(x=>{window.PRIME_CALL_LAST_START_ERROR=null;window.PRIME_CALL_START_PHASE='begin';const b=document.createElement('button');b.dataset.callStart=x;document.body.appendChild(b);b.click();b.remove()},h)}
async function accept(page){await expect(page.locator('#primecallbanner [data-call-action="accept"]')).toBeVisible({timeout:18000});await page.locator('#primecallbanner [data-call-action="accept"]').click()}
async function connected(page,t=35000){return page.waitForFunction(()=>window.PRIME?.state?.videoCall?.connected,null,{timeout:t}).then(()=>true).catch(()=>false)}
async function reset(page,t=15000){return page.waitForFunction(()=>!window.PRIME?.state?.videoCall?.call?.id&&document.getElementById('primecall')?.classList.contains('hidden'),null,{timeout:t}).then(()=>true).catch(()=>false)}
async function snap(page){return page.evaluate(()=>({phase:window.PRIME_CALL_START_PHASE||null,lastError:window.PRIME_CALL_LAST_START_ERROR||null,call:window.PRIME?.state?.videoCall?.call||null,role:window.PRIME?.state?.videoCall?.role||null,busy:!!window.PRIME?.state?.videoCall?.busy,connected:!!window.PRIME?.state?.videoCall?.connected,pc:window.PRIME?.state?.videoCall?.pc?.connectionState||null,statusText:document.querySelector('.callstatusscreen')?.innerText||document.getElementById('callstatus')?.textContent||''}))}
for(const project of ['iphone-15-pro','compact-iphone'])test(`repeat call ${project}`,async({browser,request},info)=>{if(info.project.name!==project)test.skip();test.setTimeout(150000);let q,A,B;const logs=[];try{q=await pair(request,project);A=await pageFor(browser,q.a.token,project);B=await pageFor(browser,q.b.token,project);for(const [x,w] of [[A.page,'A'],[B.page,'B']])x.on('console',m=>{if(/prime_call|turn|signal/i.test(m.text()))logs.push({who:w,type:m.type(),text:m.text().slice(0,1000)})});await start(A.page,q.b.handle);await accept(B.page);expect(await connected(A.page),'first caller connected').toBeTruthy();expect(await connected(B.page),'first callee connected').toBeTruthy();await B.page.locator('#primecall [data-call-action="hang"]').click();expect(await reset(A.page),'caller reset').toBeTruthy();expect(await reset(B.page),'callee reset').toBeTruthy();const secondStarted=Date.now();await start(A.page,q.b.handle);const outcome=await A.page.waitForFunction(()=>{const a=window.PRIME?.state?.videoCall;return a?.call?.status==='ringing'||!!window.PRIME_CALL_LAST_START_ERROR},{},{timeout:18000}).then(()=>true).catch(()=>false);const a1=await snap(A.page);console.log('REPEAT_CALL_CALLER',JSON.stringify({ms:Date.now()-secondStarted,...a1,logs}));expect(outcome,'second call reaches ringing or explicit error').toBeTruthy();expect(a1.lastError,'second caller start error').toBeNull();expect(a1.call?.status,'second call status').toBe('ringing');await accept(B.page);const ok=await Promise.all([connected(A.page,35000),connected(B.page,35000)]);const a2=await snap(A.page),b2=await snap(B.page);console.log('REPEAT_CALL_CONNECTED',JSON.stringify({ok,a2,b2,logs}));expect(ok.every(Boolean),'second call connected').toBeTruthy();await A.page.locator('#primecall [data-call-action="hang"]').click().catch(()=>{});await Promise.all([reset(A.page),reset(B.page)])}finally{await A?.c.close().catch(()=>{});await B?.c.close().catch(()=>{});await clean(request,q)}});
