import { test, expect } from '@playwright/test';
import fs from 'node:fs';
const SB='https://lqnnqsopdqnibbyzoakc.supabase.co';
const AUTH=`${SB}/functions/v1/prime-auth`,CONNECT=`${SB}/functions/v1/prime-connect`,CHAT=`${SB}/functions/v1/prime-chat`,CLEAN=`${SB}/functions/v1/prime-qa-cleanup`;
const RUN=String(process.env.GITHUB_RUN_ID||Date.now()),ATTEMPT=String(process.env.GITHUB_RUN_ATTEMPT||'1');
const post=(request,url,t,data)=>request.post(url,{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},data,timeout:25000});
async function signup(request,project,s){const tag=`${RUN.slice(-7)}${ATTEMPT}${s}${project.replace(/[^a-z0-9]/gi,'').slice(0,6)}`.slice(0,18);const q={email:`qa3-r14-${tag}@prime.invalid`,password:`PrimeR14-${tag}-X9!`,handle:`qa3_r14_${tag}`.slice(0,32),display_name:`QA3 R14 ${s.toUpperCase()}`};const r=await request.post(AUTH,{data:{action:'signup',...q},timeout:15000}),d=await r.json().catch(()=>({}));if(!r.ok()||!d?.token)throw new Error(`signup ${r.status()} ${JSON.stringify(d).slice(0,180)}`);return{...q,token:d.token}}
async function pair(request,project){const a=await signup(request,project,'a'),b=await signup(request,project,'b');let r=await post(request,CONNECT,a.token,{action:'create_invite'}),d=await r.json();r=await post(request,CONNECT,b.token,{action:'accept',code:d.code});if(!r.ok())throw new Error('accept');r=await post(request,CHAT,a.token,{action:'open',handle:b.handle});d=await r.json();const cid=d.conversation_id;if(!cid)throw new Error('open');for(let i=0;i<4;i++){let x=await post(request,CHAT,a.token,{action:'send',conversation_id:cid,body:`R14 OWN ${i+1} `+'message '.repeat(8),client_id:crypto.randomUUID()});if(!x.ok())throw new Error('seed own')}for(let i=0;i<4;i++){let x=await post(request,CHAT,b.token,{action:'send',conversation_id:cid,body:`R14 OTHER ${i+1} `+'message '.repeat(8),client_id:crypto.randomUUID()});if(!x.ok())throw new Error('seed other')}return{a,b,cid}}
async function cleanup(request,q){if(!q)return;for(const x of [q.a,q.b])await request.post(CLEAN,{headers:{Authorization:`Bearer ${x.token}`},data:{},timeout:15000}).catch(()=>null)}
async function touchHold(page,loc,ms=430){const b=await loc.boundingBox();const c=await page.context().newCDPSession(page),x=Math.round(b.x+b.width/2),y=Math.round(b.y+b.height/2);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,radiusX:2,radiusY:2,force:1,id:1}]});await page.waitForTimeout(ms);await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach()}
async function swipeLeft(page,loc){const b=await loc.boundingBox();const c=await page.context().newCDPSession(page),x=Math.round(b.x+b.width*.65),y=Math.round(b.y+b.height/2);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,radiusX:2,radiusY:2,force:1,id:1}]});for(const d of [18,38,62,88]){await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-d,y,radiusX:2,radiusY:2,force:1,id:1}]});await page.waitForTimeout(28)}await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach()}
for(const project of ['iphone-15-pro','compact-iphone'])test(`R14 critical ${project}`,async({page,request},info)=>{
 if(info.project.name!==project)test.skip();let q=null;const errors=[],http5=[];page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=500)http5.push({s:r.status(),u:r.url()})});
 try{
  q=await pair(request,project);
  await page.addInitScript(t=>localStorage.setItem('prime_token',t),q.a.token);
  await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(500);
  await page.evaluate(()=>{document.getElementById('releasegate')?.remove();document.getElementById('onboard')?.remove();document.querySelectorAll('.prime-guide').forEach(x=>x.remove())});
  await page.waitForFunction(()=>!!window.PRIME_R14_CHAT_CORE_PART1&&!!window.PRIME_CONNECT_CORE?.showRoot,null,{timeout:15000});
  await page.evaluate(h=>{window.PRIME_CONNECT_CORE.showRoot(false);window.PRIME_CONNECT_CORE.openChat(h)},q.b.handle);
  await expect(page.locator('.pc46-chatpage')).toBeVisible({timeout:15000});await page.waitForFunction(()=>document.getElementById('primeconnect')?.classList.contains('pc14-core')&&document.querySelectorAll('.pc47-msg[data-pc47-msg]').length>=8);
  const geo=await page.evaluate(()=>{const w=document.querySelector('.pc46-msgwrap.mine'),b=w?.querySelector('.pc47-msg'),wr=w?.getBoundingClientRect(),br=b?.getBoundingClientRect();return{iw:innerWidth,sw:document.documentElement.scrollWidth,padR:parseFloat(getComputedStyle(w).paddingRight),bubbleRight:br?.right,bubbleWidth:br?.width,wrapRight:wr?.right,stats:window.PRIME_CHAT_ENGINE_STATS?.()}});
  expect(geo.sw).toBeLessThanOrEqual(geo.iw+3);expect(geo.padR).toBeGreaterThanOrEqual(project==='compact-iphone'?16:19);expect(geo.iw-geo.bubbleRight).toBeGreaterThanOrEqual(project==='compact-iphone'?15:18);expect(geo.bubbleWidth).toBeLessThan(geo.iw*.80);expect(geo.stats?.version).toBe('R14-P1');expect(geo.stats?.arena).toBeTruthy();
  const input=page.locator('#pc46input');await input.focus();await page.waitForTimeout(260);const k=await page.evaluate(()=>({scale:visualViewport?.scale||1,sw:document.documentElement.scrollWidth,iw:innerWidth,font:parseFloat(getComputedStyle(document.getElementById('pc46input')).fontSize),root:document.getElementById('primeconnect').getBoundingClientRect()}));expect(Math.abs(k.scale-1)).toBeLessThan(.01);expect(k.font).toBeGreaterThanOrEqual(16);expect(k.sw).toBeLessThanOrEqual(k.iw+3);await input.blur();
  const own=page.locator('.pc46-msgwrap.mine .pc47-msg[data-pc47-msg]').filter({hasText:'R14 OWN 3'}).last();await own.scrollIntoViewIfNeeded();await touchHold(page,own);await expect(page.locator('#pc47menu')).toBeVisible({timeout:3500});expect(await page.evaluate(()=>getSelection()?.toString()||'')).toBe('');await page.mouse.click(4,4);await page.waitForTimeout(180);expect(await page.locator('#pc47menu').isVisible().catch(()=>false)).toBeFalsy();
  await swipeLeft(page,own);await page.waitForTimeout(240);expect(await page.evaluate(()=>!!window.PRIME?.state?.connect?.pc47Reply)).toBeTruthy();await page.evaluate(()=>{window.PRIME.state.connect.pc47Reply=null;window.PRIME_CONNECT_MESSENGER?.renderComposer?.(true)});
  const body=page.locator('.pc46-chatbody');for(let i=0;i<24;i++)await body.evaluate((el,i)=>{el.scrollTop=i%2?el.scrollHeight:Math.max(0,el.scrollHeight*.35)},i);await page.waitForTimeout(350);const after=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,iw:innerWidth,stats:window.PRIME_CHAT_ENGINE_STATS?.()}));expect(after.sw).toBeLessThanOrEqual(after.iw+3);expect(['idle','scroll','candidate']).toContain(after.stats?.owner);
  await input.fill('R14 LIVE SEND');await page.locator('.pc47-send').click();await expect(page.locator('.pc46-msgwrap.mine .pc47-msg').filter({hasText:'R14 LIVE SEND'}).last()).toBeVisible({timeout:10000});
  expect(errors).toEqual([]);expect(http5).toEqual([]);
  fs.mkdirSync('artifacts/r14',{recursive:true});await page.screenshot({path:`artifacts/r14/${project}.png`});fs.writeFileSync(`artifacts/r14/${project}.json`,JSON.stringify({geo,k,after,errors,http5},null,2));
 }finally{await cleanup(request,q)}
});
