import { test, expect } from '@playwright/test';
import fs from 'node:fs';

const SB='https://lqnnqsopdqnibbyzoakc.supabase.co';
const AUTH=`${SB}/functions/v1/prime-auth`,CONNECT=`${SB}/functions/v1/prime-connect`,CHAT=`${SB}/functions/v1/prime-chat`,CLEAN=`${SB}/functions/v1/prime-qa-cleanup`;
const RUN=String(process.env.GITHUB_RUN_ID||Date.now());
const post=(request,url,t,data)=>request.post(url,{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},data,timeout:25000});
const add=(a,severity,code,title,meaning,detail={})=>a.push({severity,code,title,meaning,detail});
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').slice(0,50);
async function signup(request,project,s){const tag=`${RUN.slice(-8)}${s}${slug(project).replace(/-/g,'').slice(0,8)}`.slice(0,18),q={email:`qa5-tg-${tag}@prime.invalid`,password:`PrimeTG5-${tag}-X9!`,handle:`qa5_tg_${tag}`.slice(0,32),display_name:`QA TG ${s.toUpperCase()}`};const r=await request.post(AUTH,{data:{action:'signup',...q},timeout:15000}),d=await r.json().catch(()=>({}));if(!r.ok()||!d?.token)throw new Error(`signup ${r.status()} ${JSON.stringify(d).slice(0,240)}`);return{...q,token:d.token}}
async function pair(request,project){const a=await signup(request,project,'a'),b=await signup(request,project,'b');let r=await post(request,CONNECT,a.token,{action:'create_invite'}),d=await r.json();if(!r.ok()||!d?.code)throw new Error('invite');r=await post(request,CONNECT,b.token,{action:'accept',code:d.code});d=await r.json();if(!r.ok()||!d?.ok)throw new Error('accept');r=await post(request,CHAT,a.token,{action:'open',handle:b.handle});d=await r.json();if(!r.ok()||!d?.conversation_id)throw new Error('open api');const cid=d.conversation_id;for(let i=0;i<6;i++){const who=i<3?a:b,text=(i<3?'OWN GROUP ':'OTHER GROUP ')+(i%3+1)+' · '+'message '.repeat(10);const x=await post(request,CHAT,who.token,{action:'send',conversation_id:cid,body:text,client_id:crypto.randomUUID()});if(!x.ok())throw new Error(`seed ${x.status()}`)}for(let i=0;i<8;i++){const who=i%2?a:b,text=`SCROLL QA ${i+1} `+'long chat content '.repeat(8);const x=await post(request,CHAT,who.token,{action:'send',conversation_id:cid,body:text,client_id:crypto.randomUUID()});if(!x.ok())throw new Error(`seed scroll ${x.status()}`)}return{a,b,cid}}
async function cleanup(request,q){if(!q)return;for(const x of [q.a,q.b])await request.post(CLEAN,{headers:{Authorization:`Bearer ${x.token}`},data:{},timeout:15000}).catch(()=>null)}
async function hold(page,loc,ms=470){const b=await loc.boundingBox();if(!b)return false;const c=await page.context().newCDPSession(page),x=Math.round(b.x+b.width/2),y=Math.round(b.y+b.height/2);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,radiusX:2,radiusY:2,force:1,id:1}]});await page.waitForTimeout(ms);await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach();return true}
function save(project,r){fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync(`artifacts/chat-tg-${project}.json`,JSON.stringify(r,null,2));fs.mkdirSync('artifacts/chat-tg-screens',{recursive:true})}
for(const project of ['iphone-15-pro','compact-iphone']) test(`PRIME Telegram-class chat ${project}`,async({page,request},info)=>{
  if(info.project.name!==project)test.skip();test.setTimeout(110000);const issues=[],pageErrors=[],http5=[];let q=null;const started=Date.now();
  page.on('pageerror',e=>pageErrors.push(String(e?.message||e).slice(0,1200)));page.on('response',r=>{if(r.status()>=500)http5.push({status:r.status(),url:r.url()})});
  try{
    q=await pair(request,project);
    await page.addInitScript(({token})=>{localStorage.setItem('prime_token',token);window.__qaHaptics=[];window.webkit={messageHandlers:{primeNative:{postMessage:m=>window.__qaHaptics.push(m)}}}}, {token:q.a.token});
    await page.goto('/',{waitUntil:'domcontentloaded',timeout:25000});await page.waitForTimeout(650);
    await page.evaluate(()=>{document.getElementById('releasegate')?.remove();document.getElementById('onboard')?.remove();document.querySelectorAll('.prime-guide').forEach(x=>x.remove())});
    await page.waitForFunction(()=>!!window.PRIME_CONNECT_CORE?.showRoot&&!!window.PRIME_R133_TELEGRAM_ENGINE,null,{timeout:15000});
    await page.evaluate(h=>{window.PRIME_CONNECT_CORE.showRoot(false);window.PRIME_CONNECT_CORE.openChat(h)},q.b.handle);
    await expect(page.locator('.pc46-chatpage')).toBeVisible({timeout:15000});
    await page.waitForFunction(()=>document.getElementById('primeconnect')?.classList.contains('pc133-tg')&&document.querySelectorAll('.pc47-msg[data-pc47-msg]').length>=10,null,{timeout:15000});
    const visual=await page.evaluate(()=>{const r=document.getElementById('primeconnect'),h=document.querySelector('.pc47-chathead'),c=document.querySelector('.pc47-composer'),i=document.getElementById('pc46input');return{rootClass:r?.className,sw:document.documentElement.scrollWidth,iw:innerWidth,inputFont:parseFloat(getComputedStyle(i).fontSize)||0,headBlur:getComputedStyle(h).backdropFilter||getComputedStyle(h).webkitBackdropFilter,composerBlur:getComputedStyle(c).backdropFilter||getComputedStyle(c).webkitBackdropFilter,groups:[...document.querySelectorAll('.pc46-msgwrap')].map(x=>x.dataset.pc133Group).filter(Boolean)}});
    if(visual.sw>visual.iw+3)add(issues,'HIGH','TG_HORIZONTAL_OVERFLOW','Chat is wider than viewport','Telegram-class layout must never create horizontal page drift.',visual);
    if(visual.inputFont<16)add(issues,'HIGH','TG_INPUT_ZOOM_RISK',`Input ${visual.inputFont}px`,'iOS can zoom the composer when font size is below 16px.',visual);
    if(!visual.headBlur||visual.headBlur==='none'||!visual.composerBlur||visual.composerBlur==='none')add(issues,'MEDIUM','TG_GLASS_MISSING','Glass surfaces are not active','Header and composer should use the translucent blurred surface model.',visual);
    if(!visual.groups.includes('first')||!visual.groups.includes('last'))add(issues,'MEDIUM','TG_GROUPING_MISSING','Message grouping not detected','Adjacent messages from the same sender should visually form a Telegram-style group.',visual);
    const input=page.locator('#pc46input');await input.focus();await page.waitForTimeout(220);const focus=await page.evaluate(()=>({scale:visualViewport?.scale||1,sw:document.documentElement.scrollWidth,iw:innerWidth,root:document.getElementById('primeconnect')?.getBoundingClientRect(),page:document.querySelector('.pc46-chatpage')?.getBoundingClientRect()}));
    if(Math.abs(focus.scale-1)>.01)add(issues,'HIGH','TG_KEYBOARD_SCALE','Keyboard focus changed viewport scale','Focusing the composer must not zoom the chat.',focus);
    if(focus.sw>focus.iw+3)add(issues,'HIGH','TG_KEYBOARD_OVERFLOW','Keyboard focus created horizontal overflow','Opening the keyboard must keep the chat locked to the viewport.',focus);await input.blur();
    const own=page.locator('.pc46-msgwrap.mine .pc47-msg[data-pc47-msg]').filter({hasText:'OWN GROUP 2'}).last();await expect(own).toBeVisible();const sel=await own.evaluate(el=>{const s=getComputedStyle(el),t=el.querySelector('.pc47-text'),ts=t?getComputedStyle(t):null;return{userSelect:s.userSelect,webkitUserSelect:s.webkitUserSelect,textUserSelect:ts?.userSelect}});if(sel.userSelect!=='none'&&sel.webkitUserSelect!=='none')add(issues,'HIGH','TG_NATIVE_SELECTION','Bubble is still text-selectable','Long-press should belong to PRIME reactions/actions, not iOS Copy selection.',sel);
    await hold(page,own);await expect(page.locator('#pc47menu')).toBeVisible({timeout:3500});const menu=await page.evaluate(()=>({cls:document.getElementById('pc47menu')?.className,rx:document.querySelectorAll('#pc47menu [data-pc49-react]').length,edit:!!document.querySelector('#pc47menu [data-pc47-act="edit"]'),del:!!document.querySelector('#pc47menu [data-pc47-act="delete"]'),selection:getSelection()?.toString()||'',haptics:window.__qaHaptics||[]}));if(menu.rx<7)add(issues,'HIGH','TG_REACTIONS_SHORT',`Only ${menu.rx} reactions`,'Long-press reaction row should expose the full quick reaction set.',menu);if(!menu.edit||!menu.del)add(issues,'HIGH','TG_OWN_ACTIONS_MISSING','Edit/Delete missing for own message','Own text bubble should expose Edit and Delete in the long-press menu.',menu);if(menu.selection)add(issues,'HIGH','TG_SELECTION_LEAK','Text selection survived long-press','Native selection must stay empty while PRIME context is open.',menu);if(!menu.haptics.some(x=>x?.type==='haptic'))add(issues,'MEDIUM','TG_HAPTIC_ROUTE_MISSING','No haptic bridge event on long-press','Context activation should request native haptic feedback.',menu);
    await page.mouse.click(4,Math.max(4,visual.iw/20));await page.waitForTimeout(180);if(await page.locator('#pc47menu').isVisible().catch(()=>false))add(issues,'HIGH','TG_MENU_OUTSIDE_TAP','Context menu did not dismiss','Tapping outside the Telegram-style context surface must close it.',{});
    const body=page.locator('.pc46-chatbody');await body.evaluate(el=>el.scrollTo({top:0,behavior:'auto'}));await page.waitForTimeout(220);const jumpOn=await page.locator('.pc133-jump.on').isVisible().catch(()=>false);if(!jumpOn)add(issues,'MEDIUM','TG_JUMP_BUTTON_MISSING','Scroll-to-bottom button not shown','When older messages are visible, a Telegram-style jump-to-bottom control should appear.',{});if(jumpOn){await page.locator('.pc133-jump').click();await page.waitForTimeout(420)}
    await input.fill('TG QA SEND MORPH');await page.locator('.pc47-send').click();await expect(page.locator('.pc46-msgwrap.mine .pc47-msg[data-pc47-msg]').filter({hasText:'TG QA SEND MORPH'}).last()).toBeVisible({timeout:10000});
    const path=`artifacts/chat-tg-screens/${project}-telegram-chat.png`;await page.screenshot({path,fullPage:false});
    if(pageErrors.length)add(issues,'CRITICAL','TG_PAGE_ERRORS',`JS exceptions: ${pageErrors.length}`,'The chat threw unhandled JavaScript errors.',{sample:pageErrors.slice(0,8)});if(http5.length)add(issues,'HIGH','TG_HTTP_5XX',`HTTP 5xx: ${http5.length}`,'Chat backend returned server errors.',{sample:http5.slice(0,8)});
  }catch(e){add(issues,'CRITICAL','TG_QA_ABORT','Telegram-class QA aborted','The browser scenario could not finish.',{error:String(e?.stack||e).slice(0,3500)})}
  finally{save(project,{project,duration_ms:Date.now()-started,issues});await cleanup(request,q)}
  const hard=issues.filter(x=>['CRITICAL','HIGH'].includes(x.severity));expect(hard,JSON.stringify(hard,null,2)).toEqual([]);
});
