import { test, expect } from '@playwright/test';
import fs from 'node:fs';

const SB='https://lqnnqsopdqnibbyzoakc.supabase.co';
const AUTH=`${SB}/functions/v1/prime-auth`,CONNECT=`${SB}/functions/v1/prime-connect`,CHAT=`${SB}/functions/v1/prime-chat`,CLEAN=`${SB}/functions/v1/prime-qa-cleanup`;
const RUN=String(process.env.GITHUB_RUN_ID||Date.now());
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,40)||'x';
const post=(request,url,t,data)=>request.post(url,{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},data,timeout:25000});
const add=(a,severity,code,title,meaning,detail={})=>a.push({severity,code,title,meaning,detail});

async function signup(request,project,suffix){const tag=`${String(RUN).slice(-8)}${suffix}${slug(project).replace(/-/g,'').slice(0,8)}`.slice(0,18),q={email:`qa4-chat-${tag}@prime.invalid`,password:`PrimeChat4-${tag}-X9!`,handle:`qa4_chat_${tag}`.slice(0,32),display_name:`QA 4.0 CHAT ${suffix.toUpperCase()}`};const r=await request.post(AUTH,{data:{action:'signup',...q},timeout:15000}),d=await r.json().catch(()=>({}));if(!r.ok()||!d?.token)throw new Error(`signup ${r.status()} ${JSON.stringify(d).slice(0,250)}`);return{...q,token:d.token}}
async function pair(request,project){const a=await signup(request,project,'a'),b=await signup(request,project,'b');let r=await post(request,CONNECT,a.token,{action:'create_invite'}),d=await r.json();if(!r.ok()||!d?.code)throw new Error(`invite ${r.status()}`);r=await post(request,CONNECT,b.token,{action:'accept',code:d.code});d=await r.json();if(!r.ok()||!d?.ok)throw new Error(`accept ${r.status()}`);r=await post(request,CHAT,a.token,{action:'open',handle:b.handle});d=await r.json();if(!r.ok()||!d?.conversation_id)throw new Error(`chat open ${r.status()} ${JSON.stringify(d).slice(0,250)}`);const cid=d.conversation_id;for(const [who,text] of [[a,'CHAT QA OWN MESSAGE'],[b,'CHAT QA OTHER MESSAGE']]){const x=await post(request,CHAT,who.token,{action:'send',conversation_id:cid,body:text,client_id:crypto.randomUUID()});if(!x.ok())throw new Error(`seed send ${x.status()}`)}return{a,b,cid}}
async function cleanup(request,q){if(!q)return;for(const x of [q.a,q.b])await request.post(CLEAN,{headers:{Authorization:`Bearer ${x.token}`},data:{},timeout:15000}).catch(()=>null)}
async function dismiss(page){await page.evaluate(()=>{document.getElementById('releasegate')?.remove();document.getElementById('onboard')?.remove();document.querySelectorAll('.prime-guide').forEach(x=>x.remove())}).catch(()=>{})}
async function hold(page,loc,ms=520){const b=await loc.boundingBox();if(!b)return false;const c=await page.context().newCDPSession(page),x=Math.round(b.x+b.width/2),y=Math.round(b.y+b.height/2);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,radiusX:2,radiusY:2,force:1,id:1}]});await page.waitForTimeout(ms);await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach();return true}
async function shot(page,project,name,screens){fs.mkdirSync('artifacts/chat-screens',{recursive:true});const p=`artifacts/chat-screens/${slug(project)}-${slug(name)}.png`;await page.screenshot({path:p});screens.push(p)}
function save(project,r){fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync(`artifacts/chat-${project}.json`,JSON.stringify(r,null,2));const c=r.issues.reduce((a,x)=>(a[x.severity]=(a[x.severity]||0)+1,a),{}),out=[`# PRIME Chat Deep QA — ${project}`,'',`- Issues: ${r.issues.length} (CRITICAL ${c.CRITICAL||0}, HIGH ${c.HIGH||0}, MEDIUM ${c.MEDIUM||0}, LOW ${c.LOW||0})`,`- Context menu: ${r.context_menu_ok}`,`- Native selection blocked: ${r.selection_blocked}`,`- Input font: ${r.input_font_px}px`,`- Send/edit/reply/delete: ${r.actions_ok}`,'','## Bugs',''];if(!r.issues.length)out.push('Подтверждённых проблем не найдено.');r.issues.forEach((x,i)=>out.push(`### CHAT-${String(i+1).padStart(3,'0')} · ${x.severity} · ${x.code}`,`**Баг:** ${x.title}`,`**Что это значит:** ${x.meaning}`,`**Детали:** \`${JSON.stringify(x.detail).slice(0,1800)}\``,''));fs.writeFileSync(`artifacts/chat-${project}.md`,out.join('\n'))}

for(const project of ['iphone-15-pro','compact-iphone'])test(`PRIME Chat iOS deep QA ${project}`,async({page,request},info)=>{if(info.project.name!==project)test.skip();test.setTimeout(150000);const started=Date.now(),issues=[],screens=[],pageErrors=[],http5=[];let q=null,contextOk=false,selectionBlocked=false,inputFont=0,actionsOk=false;page.on('pageerror',e=>pageErrors.push(String(e?.message||e).slice(0,1200)));page.on('response',r=>{if(r.status()>=500)http5.push({status:r.status(),url:r.url()})});try{
 q=await pair(request,project);await page.addInitScript(t=>localStorage.setItem('prime_token',t),q.a.token);await page.goto('/',{waitUntil:'domcontentloaded',timeout:25000});await page.waitForTimeout(800);await dismiss(page);await page.waitForFunction(()=>!!window.PRIME_CONNECT_CORE?.showRoot&&!!window.PRIME_R132_CHAT_IOS_GESTURE_VIEWPORT_FIX,null,{timeout:15000});await page.evaluate(h=>{window.PRIME_CONNECT_CORE.showRoot(false);return window.PRIME_CONNECT_CORE.openChat(h)},q.b.handle);await expect(page.locator('.pc46-chatpage')).toBeVisible({timeout:12000});await page.waitForFunction(()=>window.PRIME_CHAT_ENGINE_V2?.mounted&&document.querySelectorAll('.pc47-msg[data-pc47-msg]').length>=2,null,{timeout:15000});await shot(page,project,'opened',screens);
 const own=page.locator('.pc46-msgwrap.mine .pc47-msg[data-pc47-msg]').filter({hasText:'CHAT QA OWN MESSAGE'}).last(),other=page.locator('.pc46-msgwrap.theirs .pc47-msg[data-pc47-msg]').filter({hasText:'CHAT QA OTHER MESSAGE'}).last();await expect(own).toBeVisible();await expect(other).toBeVisible();
 const css=await own.evaluate(el=>{const c=getComputedStyle(el),t=el.querySelector('.pc47-text'),tc=t?getComputedStyle(t):null;return{userSelect:c.userSelect,webkitUserSelect:c.webkitUserSelect,touchCallout:c.webkitTouchCallout,textUserSelect:tc?.userSelect,textTouchCallout:tc?.webkitTouchCallout}});if(css.userSelect!=='none'||css.webkitUserSelect!=='none')add(issues,'HIGH','NATIVE_SELECTION_CSS_OPEN','Message bubble still selectable','iOS can steal long-press for native Copy/selection instead of PRIME reactions.',css);
 selectionBlocked=await own.evaluate(el=>new Promise(resolve=>{const n=el.querySelector('.pc47-text')||el,s=getSelection(),r=document.createRange();r.selectNodeContents(n);s.removeAllRanges();s.addRange(r);document.dispatchEvent(new Event('selectionchange'));setTimeout(()=>resolve(!getSelection()||getSelection().isCollapsed||getSelection().rangeCount===0),60)}));if(!selectionBlocked)add(issues,'HIGH','NATIVE_SELECTION_SURVIVES','Native text selection remains active','After selecting message text, PRIME did not clear the browser selection.',{});
 const input=page.locator('#pc46input');inputFont=await input.evaluate(el=>parseFloat(getComputedStyle(el).fontSize)||0);if(inputFont<16)add(issues,'HIGH','IOS_FOCUS_ZOOM_RISK',`Input font ${inputFont}px`,'iOS Safari zooms form fields below 16px when the keyboard opens.',{inputFont});const vp=await page.locator('meta[name="viewport"]').getAttribute('content');if(!/initial-scale=1/.test(vp||'')||!/maximum-scale=1/.test(vp||''))add(issues,'MEDIUM','VIEWPORT_ZOOM_GUARD_MISSING','Viewport zoom guard incomplete','Chat can visually scale when the keyboard focuses the composer.',{viewport:vp});await input.focus();await page.waitForTimeout(250);const focusGeom=await page.evaluate(()=>({scale:visualViewport?.scale||1,root:document.getElementById('primeconnect')?.getBoundingClientRect(),page:document.querySelector('.pc46-chatpage')?.getBoundingClientRect(),input:document.getElementById('pc46input')?.getBoundingClientRect(),sw:document.documentElement.scrollWidth,iw:innerWidth}));if(Math.abs(Number(focusGeom.scale||1)-1)>.01)add(issues,'HIGH','FOCUS_SCALE_CHANGED','Focus changed visualViewport scale','Keyboard focus must not zoom PRIME.',focusGeom);if(focusGeom.sw>focusGeom.iw+3)add(issues,'HIGH','FOCUS_HORIZONTAL_OVERFLOW','Keyboard focus creates horizontal overflow','Composer focus should not widen/zoom the chat.',focusGeom);await shot(page,project,'input-focused',screens);await input.blur();
 await hold(page,own);contextOk=await page.locator('#pc47menu.pc131-context-layer').isVisible().catch(()=>false);if(!contextOk)add(issues,'CRITICAL','LONG_PRESS_NATIVE_INSTEAD_OF_PRIME','Long-press did not open PRIME menu','Holding a message must open reactions/actions instead of iOS text selection/copy.',{});if(contextOk){const rx=await page.locator('#pc47menu [data-pc49-react]').count(),del=await page.locator('#pc47menu [data-pc47-act="delete"]').count();if(rx<7)add(issues,'HIGH','REACTION_BAR_INCOMPLETE',`Reaction buttons: ${rx}`,'Long-press menu should expose the PRIME reaction row.',{rx});if(!del)add(issues,'HIGH','OWN_DELETE_MISSING','Delete missing on own message','Own message context menu must contain Delete.',{});await shot(page,project,'longpress-menu',screens);await page.locator('#pc47menu [data-pc49-react]').first().click();await page.waitForTimeout(450)}
 await hold(page,other);if(await page.locator('#pc47menu').isVisible().catch(()=>false)){if(await page.locator('#pc47menu [data-pc47-act="delete"]').count())add(issues,'HIGH','FOREIGN_DELETE_EXPOSED','Delete shown for incoming message','A user must not get Delete-for-all action on the other participant’s message.',{});await page.locator('#pc47menu [data-pc47-act="reply"]').click();await expect(page.locator('.pc47-context')).toBeVisible({timeout:3000});await input.fill('CHAT QA REPLY');await page.locator('.pc47-send').click();await expect(page.locator('.pc47-msg').filter({hasText:'CHAT QA REPLY'}).last()).toBeVisible({timeout:8000})}else add(issues,'HIGH','OTHER_LONG_PRESS_FAILED','Incoming message long-press failed','Context menu should work on received messages too.',{});
 await input.fill('CHAT QA EDIT ME');await page.locator('.pc47-send').click();const editMsg=page.locator('.pc46-msgwrap.mine .pc47-msg[data-pc47-msg]').filter({hasText:'CHAT QA EDIT ME'}).last();await expect(editMsg).toBeVisible({timeout:8000});await hold(page,editMsg);if(await page.locator('#pc47menu [data-pc47-act="edit"]').isVisible().catch(()=>false)){await page.locator('#pc47menu [data-pc47-act="edit"]').click();await input.fill('CHAT QA EDITED');await page.locator('.pc47-send').click();await expect(page.locator('.pc47-msg').filter({hasText:'CHAT QA EDITED'}).last()).toBeVisible({timeout:8000})}else add(issues,'HIGH','EDIT_ACTION_MISSING','Edit missing for own text','Own text message should be editable from long-press menu.',{});
 const edited=page.locator('.pc46-msgwrap.mine .pc47-msg[data-pc47-msg]').filter({hasText:'CHAT QA EDITED'}).last();await hold(page,edited);if(await page.locator('#pc47menu [data-pc47-act="delete"]').isVisible().catch(()=>false)){await page.locator('#pc47menu [data-pc47-act="delete"]').click();await expect(page.locator('.pc46-msgwrap.mine .pc47-msg').filter({hasText:'Сообщение удалено'}).last()).toBeVisible({timeout:8000})}else add(issues,'HIGH','DELETE_ACTION_UNUSABLE','Delete action could not be used','Own message should delete from the PRIME long-press menu.',{});
 const model=await page.evaluate(()=>{const ms=window.PRIME?.state?.connect?.open?.messages||[];return{reply:ms.some(m=>m.body==='CHAT QA REPLY'&&m.reply_to_id),edited:ms.some(m=>m.body==='CHAT QA EDITED'&&m.edited_at),deleted:ms.some(m=>m.body===''&&m.deleted_for_all_at),reaction:ms.some(m=>(m.reactions||[]).length)}});actionsOk=!!(model.reply&&model.deleted&&model.reaction);if(!model.reply)add(issues,'HIGH','REPLY_NOT_PERSISTED','Reply relation missing','Reply was visible but reply_to_id was not retained in chat state.',model);if(!model.deleted)add(issues,'HIGH','DELETE_NOT_PERSISTED','Delete state missing','Deleted message did not retain deleted_for_all_at.',model);if(!model.reaction)add(issues,'MEDIUM','REACTION_NOT_PERSISTED','Reaction missing after tap','Reaction menu opened but reaction did not persist in state.',model);await shot(page,project,'final',screens);
 if(pageErrors.length)add(issues,'CRITICAL','CHAT_PAGE_ERRORS',`JS exceptions: ${pageErrors.length}`,'Chat threw unhandled JavaScript errors.',{sample:pageErrors.slice(0,8)});if(http5.length)add(issues,'HIGH','CHAT_HTTP_5XX',`HTTP 5xx: ${http5.length}`,'Chat backend returned server errors.',{sample:http5.slice(0,8)});
 }catch(e){add(issues,'CRITICAL','CHAT_QA_FATAL','Chat Deep QA aborted','The browser scenario could not finish.',{error:String(e?.stack||e).slice(0,4000)})}finally{const report={project,duration_ms:Date.now()-started,context_menu_ok:contextOk,selection_blocked:selectionBlocked,input_font_px:inputFont,actions_ok:actionsOk,issues,screens};save(project,report);await cleanup(request,q)}const hard=issues.filter(x=>['CRITICAL','HIGH'].includes(x.severity));expect(hard,JSON.stringify(hard,null,2)).toEqual([])});
