import { test, expect } from '@playwright/test';
import fs from 'node:fs';
const SB='https://lqnnqsopdqnibbyzoakc.supabase.co';
const AUTH=`${SB}/functions/v1/prime-auth`,CONNECT=`${SB}/functions/v1/prime-connect`,CHAT=`${SB}/functions/v1/prime-chat`,CLEAN=`${SB}/functions/v1/prime-qa-cleanup`;
const RUN=String(process.env.GITHUB_RUN_ID||Date.now());
const post=(request,url,t,data)=>request.post(url,{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},data,timeout:25000});
async function signup(request,project,s){const rnd=crypto.randomUUID().replace(/-/g,'').slice(0,8),tag=`${RUN.slice(-6)}${s}${project.replace(/[^a-z0-9]/gi,'').slice(0,5)}${rnd}`.slice(0,22);const q={email:`qa3-p2-${tag}@prime.invalid`,password:`PrimeP2-${tag}-X9!`,handle:`qa3_p2_${tag}`.slice(0,32),display_name:`QA3 P2 ${s.toUpperCase()}`};const r=await request.post(AUTH,{data:{action:'signup',...q},timeout:15000}),d=await r.json().catch(()=>({}));if(!r.ok()||!d?.token)throw new Error(`signup ${r.status()} ${JSON.stringify(d).slice(0,180)}`);return{...q,token:d.token}}
async function pair(request,project){const a=await signup(request,project,'a'),b=await signup(request,project,'b');let r=await post(request,CONNECT,a.token,{action:'create_invite'}),d=await r.json();if(!r.ok()||!d?.code)throw new Error('invite');r=await post(request,CONNECT,b.token,{action:'accept',code:d.code});if(!r.ok())throw new Error('accept');r=await post(request,CHAT,a.token,{action:'open',handle:b.handle});d=await r.json();const cid=d.conversation_id;if(!cid)throw new Error('open');const own=[];for(let i=0;i<3;i++){const x=await post(request,CHAT,a.token,{action:'send',conversation_id:cid,body:`P2 OWN ${i+1} `+'message '.repeat(7),client_id:crypto.randomUUID()});const j=await x.json();if(!x.ok()||!j.message)throw new Error('seed own');own.push(j.message)}const other=[];for(let i=0;i<9;i++){const x=await post(request,CHAT,b.token,{action:'send',conversation_id:cid,body:`P2 OTHER ${i+1} `+'long unread content '.repeat(6),client_id:crypto.randomUUID()});const j=await x.json();if(!x.ok()||!j.message)throw new Error('seed other');other.push(j.message)}const reply=await post(request,CHAT,b.token,{action:'send',conversation_id:cid,body:'P2 REPLY TARGET',client_id:crypto.randomUUID(),reply_to_id:own[0].id});if(!reply.ok())throw new Error('seed reply');return{a,b,cid,own,other}}
async function cleanup(request,q){if(!q)return;for(const x of [q.a,q.b])await request.post(CLEAN,{headers:{Authorization:`Bearer ${x.token}`},data:{},timeout:15000}).catch(()=>null)}
async function hold(page,loc,ms=390){const b=await loc.boundingBox();if(!b)throw new Error('no bubble box');const c=await page.context().newCDPSession(page),x=Math.round(b.x+b.width/2),y=Math.round(b.y+b.height/2);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,radiusX:2,radiusY:2,force:1,id:1}]});await page.waitForTimeout(ms);await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach()}
for(const project of ['iphone-15-pro','compact-iphone'])test(`R14 P2 ${project}`,async({page,request},info)=>{
 if(info.project.name!==project)test.skip();test.setTimeout(120000);let q=null;const errors=[],http5=[];page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=500)http5.push({s:r.status(),u:r.url()})});
 try{
  q=await pair(request,project);
  await page.addInitScript(t=>localStorage.setItem('prime_token',t),q.a.token);
  await page.goto('/',{waitUntil:'domcontentloaded',timeout:25000});await page.waitForTimeout(650);
  await page.evaluate(()=>{document.getElementById('releasegate')?.remove();document.getElementById('onboard')?.remove();document.querySelectorAll('.prime-guide').forEach(x=>x.remove())});
  await page.waitForFunction(()=>!!window.PRIME_R14_PART2_MESSENGER&&!!window.PRIME_CONNECT_CORE?.showRoot,null,{timeout:15000});
  await page.evaluate(()=>window.PRIME_CONNECT_CORE.showRoot(false));
  const row=page.locator(`.pc46-chatrow[data-pc46-chat="${q.b.handle}"]`);await expect(row).toBeVisible({timeout:15000});await row.tap();
  await expect(page.locator('.pc46-chatpage')).toBeVisible({timeout:15000});await page.waitForFunction(()=>document.getElementById('primeconnect')?.classList.contains('pc14-p2')&&document.querySelectorAll('.pc47-msg[data-pc47-msg]').length>=10,null,{timeout:15000});
  await expect(page.locator('.pc14-unread-start')).toHaveCount(1,{timeout:5000});
  const input=page.locator('#pc46input');await input.fill('P2 SAVED DRAFT');await page.waitForTimeout(120);await page.locator('[data-pc46-back]').tap();await expect(page.locator('.pc46-chatpage')).toHaveCount(0,{timeout:5000});await page.evaluate(()=>{window.PRIME.state.connect.pc47Draft='';});await page.evaluate(h=>window.PRIME_CONNECT_CORE.openChat(h),q.b.handle);await expect(page.locator('#pc46input')).toHaveValue('P2 SAVED DRAFT',{timeout:10000});await input.fill('');await page.waitForTimeout(100);
  await input.fill('P2 RECEIPT MESSAGE');await page.locator('.pc47-send').tap();const sent=page.locator('.pc46-msgwrap.mine .pc47-msg[data-pc47-msg]').filter({hasText:'P2 RECEIPT MESSAGE'}).last();await expect(sent).toBeVisible({timeout:10000});await expect(sent.locator('.pc14-receipt')).toContainText('✓',{timeout:4000});
  let rr=await post(request,CHAT,q.b.token,{action:'read',conversation_id:q.cid});if(!rr.ok())throw new Error('peer read failed');await expect(sent.locator('.pc14-receipt.read')).toHaveText('✓✓',{timeout:9000});
  await post(request,CHAT,q.b.token,{action:'typing',conversation_id:q.cid,typing:true,kind:'text'});await expect(page.locator('.pc46-chatname span.pc14-typing')).toBeVisible({timeout:7000});await post(request,CHAT,q.b.token,{action:'typing',conversation_id:q.cid,typing:false,kind:'text'});
  const reply=page.locator('.pc47-msg').filter({hasText:'P2 REPLY TARGET'}).last();await expect(reply).toBeVisible();const quote=reply.locator('[data-pc49-reply-to]');await expect(quote).toBeVisible();await quote.tap();await page.waitForTimeout(650);const original=page.locator(`.pc47-msg[data-pc47-msg="${q.own[0].id}"]`);await expect(original).toBeVisible({timeout:5000});
  await sent.scrollIntoViewIfNeeded();await hold(page,sent);await expect(page.locator('#pc47menu')).toBeVisible({timeout:3500});const rx=page.locator('#pc47menu [data-pc49-react="🔥"]');await rx.tap();await expect(page.locator('.pc49-reactions [data-pc49-chip="🔥"]')).toBeVisible({timeout:6000});
  await hold(page,sent);await expect(page.locator('#pc47menu')).toBeVisible();await page.locator('#pc47menu [data-pc47-act="edit"]').tap();await expect(input).toHaveValue('P2 RECEIPT MESSAGE');await input.fill('P2 RECEIPT EDITED');await page.locator('.pc47-send').tap();await expect(page.locator('.pc47-msg').filter({hasText:'P2 RECEIPT EDITED'}).last()).toBeVisible({timeout:7000});
  const own2=page.locator(`.pc47-msg[data-pc47-msg="${q.own[1].id}"]`);await own2.scrollIntoViewIfNeeded();await hold(page,own2);await page.locator('#pc47menu [data-pc49-pin]').tap();await expect(page.locator('.pc49-pinned')).toBeVisible({timeout:6000});
  await hold(page,own2);await page.locator('#pc47menu [data-pc47-act="delete"]').tap();await expect(own2).toContainText('Сообщение удалено',{timeout:7000});
  const layout=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,iw:innerWidth,p2:window.PRIME_CHAT_P2?.version,stats:window.PRIME_CHAT_ENGINE_STATS?.()}));expect(layout.sw).toBeLessThanOrEqual(layout.iw+3);expect(layout.p2).toBe('R14-P2');expect(errors).toEqual([]);expect(http5).toEqual([]);
  fs.mkdirSync('artifacts/r14p2',{recursive:true});await page.screenshot({path:`artifacts/r14p2/${project}.png`});fs.writeFileSync(`artifacts/r14p2/${project}.json`,JSON.stringify({layout,errors,http5},null,2));
 }finally{await cleanup(request,q)}
});
