import { test, expect } from '@playwright/test';

const SB='https://lqnnqsopdqnibbyzoakc.supabase.co';
const AUTH=`${SB}/functions/v1/prime-auth`,CONNECT=`${SB}/functions/v1/prime-connect`,CHAT=`${SB}/functions/v1/prime-chat`,CLEAN=`${SB}/functions/v1/prime-qa-cleanup`;
const RUN=String(process.env.GITHUB_RUN_ID||Date.now());
const post=(request,url,t,data)=>request.post(url,{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},data,timeout:25000});
async function signup(request,s){const tag=`${RUN.slice(-8)}${s}edit`;const q={email:`qa4-chat-edit-${tag}@prime.invalid`,password:`PrimeChatEdit-${tag}-X9!`,handle:`qa4_chat_edit_${tag}`.slice(0,32),display_name:`QA 4.0 CHAT EDIT ${s.toUpperCase()}`};const r=await request.post(AUTH,{data:{action:'signup',...q},timeout:15000}),d=await r.json();if(!r.ok()||!d.token)throw new Error(`signup ${r.status()} ${JSON.stringify(d)}`);return{...q,token:d.token}}
async function pair(request){const a=await signup(request,'a'),b=await signup(request,'b');let r=await post(request,CONNECT,a.token,{action:'create_invite'}),d=await r.json();r=await post(request,CONNECT,b.token,{action:'accept',code:d.code});d=await r.json();if(!r.ok()||!d.ok)throw new Error(`pair ${r.status()} ${JSON.stringify(d)}`);r=await post(request,CHAT,a.token,{action:'open',handle:b.handle});d=await r.json();return{a,b,cid:d.conversation_id}}
async function clean(request,q){if(!q)return;for(const x of [q.a,q.b])await request.post(CLEAN,{headers:{Authorization:`Bearer ${x.token}`},data:{},timeout:15000}).catch(()=>{})}
async function hold(page,loc,ms=520){const b=await loc.boundingBox();if(!b)throw new Error('no bbox');const c=await page.context().newCDPSession(page),x=Math.round(b.x+b.width/2),y=Math.round(b.y+b.height/2);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,radiusX:2,radiusY:2,force:1,id:1}]});await page.waitForTimeout(ms);await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach()}
async function snap(page,text){return page.evaluate(t=>{const C=window.PRIME?.state?.connect,E=window.PRIME_CHAT_ENGINE_V2,OS=window.PRIME_CHAT_OS;const bubble=[...document.querySelectorAll('.pc47-msg[data-pc47-msg]')].find(x=>x.textContent.includes(t));const id=bubble?.dataset.pc47Msg||null,m=(C?.open?.messages||[]).find(x=>String(x.id)===String(id))||null,em=id?E?.byId?.get?.(String(id)):null,menu=document.getElementById('pc47menu');return{t,id,bubbleClass:bubble?.className||null,bubbleWrap:bubble?.closest('.pc46-msgwrap')?.className||null,Cme:C?.me?.id||null,msg:m?{id:m.id,sender_id:m.sender_id,body:m.body,message_type:m.message_type,_sending:m._sending,_failed:m._failed,deleted_for_all_at:m.deleted_for_all_at,edited_at:m.edited_at}:null,engine:em?{id:em.id,sender_id:em.sender_id,body:em.body,message_type:em.message_type,_sending:em._sending,_failed:em._failed,deleted_for_all_at:em.deleted_for_all_at,edited_at:em.edited_at}:null,contextOpen:!!OS?.contextOpen,owner:OS?.owner||null,gesture:E?.gesture?{type:E.gesture.type,id:E.gesture.id,mode:E.gesture.mode,long:E.gesture.long}:null,menu:menu?{className:menu.className,messageId:menu.dataset.messageId,buttons:[...menu.querySelectorAll('button')].map(b=>({text:b.textContent.trim(),act:b.dataset.pc47Act||null,rx:b.dataset.pc49React||null}))}:null};},text)}

test('compact edit menu diagnostic',async({page,request})=>{test.setTimeout(120000);let q;try{q=await pair(request);await post(request,CHAT,q.b.token,{action:'send',conversation_id:q.cid,body:'EDIT DIAG OTHER',client_id:crypto.randomUUID()});await page.addInitScript(t=>localStorage.setItem('prime_token',t),q.a.token);await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(700);await page.evaluate(()=>{document.getElementById('releasegate')?.remove();document.getElementById('onboard')?.remove()});await page.waitForFunction(()=>!!window.PRIME_CONNECT_CORE?.showRoot&&!!window.PRIME_R132_CHAT_IOS_GESTURE_VIEWPORT_FIX);await page.evaluate(h=>{window.PRIME_CONNECT_CORE.showRoot(false);return window.PRIME_CONNECT_CORE.openChat(h)},q.b.handle);await page.waitForFunction(()=>window.PRIME_CHAT_ENGINE_V2?.mounted&&[...document.querySelectorAll('.pc47-msg[data-pc47-msg]')].some(x=>x.textContent.includes('EDIT DIAG OTHER')));
const other=page.locator('.pc47-msg[data-pc47-msg]').filter({hasText:'EDIT DIAG OTHER'}).last();await hold(page,other);await expect(page.locator('#pc47menu')).toBeVisible();console.log('DIAG_OTHER_MENU',JSON.stringify(await snap(page,'EDIT DIAG OTHER')));await page.locator('#pc47menu [data-pc47-act="reply"]').click();const input=page.locator('#pc46input');await input.fill('EDIT DIAG REPLY');await page.locator('.pc47-send').click();await expect(page.locator('.pc47-msg[data-pc47-msg]').filter({hasText:'EDIT DIAG REPLY'}).last()).toBeVisible({timeout:10000});
for(let i=0;i<4;i++){const text=`EDIT DIAG OWN ${i}`;await input.fill(text);await page.locator('.pc47-send').click();const loc=page.locator('.pc46-msgwrap.mine .pc47-msg[data-pc47-msg]').filter({hasText:text}).last();await expect(loc).toBeVisible({timeout:10000});await page.waitForTimeout(120);console.log('DIAG_BEFORE_HOLD',i,JSON.stringify(await snap(page,text)));await hold(page,loc);await page.waitForTimeout(120);const s=await snap(page,text);console.log('DIAG_AFTER_HOLD',i,JSON.stringify(s));if(!s.menu){console.log('DIAG_NO_MENU',i);continue}const edit=s.menu.buttons.some(b=>b.act==='edit');console.log('DIAG_EDIT_PRESENT',i,edit);if(edit){await page.locator('#pc47menu [data-pc47-act="edit"]').click();await page.waitForTimeout(80);console.log('DIAG_AFTER_EDIT_CLICK',i,JSON.stringify({draft:await input.inputValue(),state:await page.evaluate(()=>({edit:window.PRIME?.state?.connect?.pc47Edit?.id||null,reply:window.PRIME?.state?.connect?.pc47Reply?.id||null,context:window.PRIME_CHAT_OS?.contextOpen,owner:window.PRIME_CHAT_OS?.owner}))}));await page.locator('[data-pc47-context-close]').click().catch(()=>{});await page.waitForTimeout(100)}else{await page.mouse.click(3,3);await page.waitForTimeout(160)}}
}finally{await clean(request,q)}});
