import { test, expect } from '@playwright/test';
import fs from 'node:fs';

const SB='https://lqnnqsopdqnibbyzoakc.supabase.co';
const AUTH=`${SB}/functions/v1/prime-auth`,CONNECT=`${SB}/functions/v1/prime-connect`,CHAT=`${SB}/functions/v1/prime-chat`,FIXTURE=`${SB}/functions/v1/prime-qa-contact-fixture`,CLEAN=`${SB}/functions/v1/prime-qa-cleanup`;
const RUN=String(process.env.GITHUB_RUN_ID||Date.now());
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,50)||'x';
const add=(xs,severity,code,title,meaning,detail={})=>xs.push({severity,code,title,meaning,detail});
const post=(request,url,token,data,headers={})=>request.post(url,{headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...headers},data});

async function signup(request,project,suffix){
 const p=slug(project).replace(/-/g,'').slice(0,9),tag=`${String(RUN).slice(-8)}${suffix}${p}`.slice(0,20),q={email:`qa2-contact-${tag}@prime.invalid`,password:`PrimeQA-${tag}-X9!`,handle:`qa2_${tag}`.slice(0,32),display_name:`QA 2.0 ${suffix.toUpperCase()} ${p}`.slice(0,32)};
 let r=await request.post(AUTH,{data:{action:'signup',...q}}),d=await r.json().catch(()=>({}));if(!r.ok()||!d?.token)throw new Error(`signup ${suffix} failed ${r.status()} ${JSON.stringify(d).slice(0,250)}`);return{...q,token:d.token,profile:d.profile||null};
}
async function pair(request,project){
 const a=await signup(request,project,'a'),b=await signup(request,project,'b');
 let r=await post(request,CONNECT,a.token,{action:'create_invite'}),d=await r.json();if(!r.ok()||!d?.code)throw new Error(`invite failed ${r.status()} ${JSON.stringify(d)}`);
 r=await post(request,CONNECT,b.token,{action:'accept',code:d.code});const accepted=await r.json();if(!r.ok()||!accepted?.ok)throw new Error(`accept failed ${r.status()} ${JSON.stringify(accepted)}`);
 r=await post(request,FIXTURE,a.token,{action:'seed',count:500},{'x-peer-token':b.token});const seeded=await r.json();if(!r.ok()||seeded?.count<530)throw new Error(`fixture failed ${r.status()} ${JSON.stringify(seeded).slice(0,500)}`);
 return{a,b,seeded};
}
async function cleanup(request,x){
 if(!x)return;await post(request,FIXTURE,x.a.token,{action:'cleanup'},{'x-peer-token':x.b.token}).catch(()=>null);
 for(const q of [x.a,x.b])await request.post(CLEAN,{headers:{Authorization:`Bearer ${q.token}`},data:{}}).catch(()=>null);
}
async function dismiss(page){for(const s of ['#releasecontinue','[data-prime-guide="skip"]','[data-action="onboard-skip"]','button:has-text("ПРОПУСТИТЬ")','button:has-text("Пропустить")']){const e=page.locator(s).first();if(await e.isVisible().catch(()=>false))await e.click({timeout:1200}).catch(()=>null)}}
async function audit(page,label,issues,screens,project){
 const a=await page.evaluate(()=>{const root=document.getElementById('primeconnect'),vis=e=>{if(!e)return false;const c=getComputedStyle(e),r=e.getBoundingClientRect();return c.display!=='none'&&c.visibility!=='hidden'&&+c.opacity!==0&&r.width>0&&r.height>0},vw=innerWidth,vh=innerHeight,covered=[],off=[];for(const e of [...(root?.querySelectorAll('button,a,input,textarea,[role="button"]')||[])].filter(vis)){const r=e.getBoundingClientRect(),n=(e.getAttribute('aria-label')||e.textContent||e.id||e.tagName).trim().replace(/\s+/g,' ').slice(0,90);if(r.left<-3||r.right>vw+3)off.push({name:n,left:Math.round(r.left),right:Math.round(r.right)});if(r.bottom<0||r.top>vh)continue;const x=Math.max(1,Math.min(vw-1,r.left+r.width/2)),y=Math.max(1,Math.min(vh-1,r.top+r.height/2)),top=document.elementFromPoint(x,y);if(top&&!(top===e||e.contains(top)||top.contains(e)))covered.push({name:n,coveredBy:(top.getAttribute?.('aria-label')||top.textContent||top.id||top.className||top.tagName).toString().trim().replace(/\s+/g,' ').slice(0,100)})}const comp=root?.querySelector('.pc47-composer,.pc46-composer'),cr=comp?.getBoundingClientRect();return{rootVisible:vis(root)&&!root.classList.contains('hidden'),chatPages:root?.querySelectorAll('.pc46-chatpage').length||0,composers:root?.querySelectorAll('.pc47-composer,.pc46-composer').length||0,menus:root?.querySelectorAll('#pc47menu').length||0,overflow:Math.max(0,(root?.scrollWidth||0)-vw),covered,off,composer:cr?{top:Math.round(cr.top),bottom:Math.round(cr.bottom),height:Math.round(cr.height),vh}:null,failedMedia:root?.querySelectorAll('.pc131-media-failed').length||0,brokenImages:[...(root?.querySelectorAll('img')||[])].filter(vis).filter(i=>i.complete&&(!i.naturalWidth||!i.naturalHeight)).length};});
 const file=`artifacts/contact-screens/${slug(project)}-${slug(label)}.png`;fs.mkdirSync('artifacts/contact-screens',{recursive:true});await page.screenshot({path:file,fullPage:false});screens.push({label,screenshot:file,audit:a});
 if(!a.rootVisible)add(issues,'CRITICAL','CONTACT_ROOT_HIDDEN',`${label}: PRIME Contact исчез`,'Корневой интерфейс мессенджера неожиданно скрыт.');if(a.chatPages>1)add(issues,'HIGH','DUPLICATE_CHAT_PAGE',`${label}: открыто ${a.chatPages} chat pages`,'Быстрые действия создали дубликат экрана чата.');if(a.composers>1)add(issues,'HIGH','DUPLICATE_COMPOSER',`${label}: несколько composer`,'В DOM одновременно существует несколько полей отправки.');if(a.overflow>3)add(issues,'HIGH','CONTACT_HORIZONTAL_OVERFLOW',`${label}: горизонтальный overflow ${a.overflow}px`,'Мессенджер шире экрана iPhone.');if(a.covered.length)add(issues,'HIGH','CONTACT_COVERED_TAP',`${label}: перекрыты кнопки`,'Видимый контрол получает hit-test через другой слой.',{elements:a.covered.slice(0,12)});if(a.off.length)add(issues,'MEDIUM','CONTACT_OFFSCREEN',`${label}: элементы за viewport`,'Часть интерактивного элемента уехала за экран.',{elements:a.off.slice(0,12)});if(a.composer&&a.composer.bottom>a.composer.vh+3)add(issues,'HIGH','COMPOSER_BELOW_VIEWPORT',`${label}: composer ушёл под viewport`,'Поле сообщения/кнопка отправки оказываются под нижней границей экрана.',a.composer);return a;
}
function save(project,r){fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync(`artifacts/contact-${project}.json`,JSON.stringify(r,null,2));const c=r.issues.reduce((a,x)=>(a[x.severity]=(a[x.severity]||0)+1,a),{}),o=[`# PRIME Contact Deep QA — ${project}`,'',`- Seeded: ${r.seeded||0} messages`,`- Loaded history: ${r.loaded_history||0}`,`- Screens: ${r.screens.length}`,`- Issues: ${r.issues.length} (CRITICAL ${c.CRITICAL||0}, HIGH ${c.HIGH||0}, MEDIUM ${c.MEDIUM||0}, LOW ${c.LOW||0})`,'','## Bugs',''];if(!r.issues.length)o.push('Подтверждённых проблем не найдено.');r.issues.forEach((x,i)=>o.push(`### CONTACT-${String(i+1).padStart(3,'0')} · ${x.severity} · ${x.code}`,`**Баг:** ${x.title}`,`**Что это значит:** ${x.meaning}`,`**Детали:** \`${JSON.stringify(x.detail).slice(0,1800)}\``,''));fs.writeFileSync(`artifacts/contact-${project}.md`,o.join('\n'))}

async function touchHold(page,loc,ms=650){const b=await loc.boundingBox();if(!b)return false;const x=b.x+b.width/2,y=b.y+b.height/2;await loc.dispatchEvent('pointerdown',{pointerId:71,pointerType:'touch',isPrimary:true,clientX:x,clientY:y,buttons:1});await page.waitForTimeout(ms);await loc.dispatchEvent('pointerup',{pointerId:71,pointerType:'touch',isPrimary:true,clientX:x,clientY:y,buttons:0});return true}

test('PRIME Contact deep messenger QA',async({page,request},info)=>{
 test.setTimeout(210000);const project=info.project.name,issues=[],screens=[],consoleErrors=[],pageErrors=[],requestFailures=[],http5=[],started=Date.now();let fx=null,loaded=0,simulatedAbort=false;
 page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text().slice(0,800))});page.on('pageerror',e=>pageErrors.push(String(e?.message||e).slice(0,1000)));page.on('requestfailed',r=>{if(!simulatedAbort)requestFailures.push({url:r.url(),error:r.failure()?.errorText})});page.on('response',r=>{if(r.status()>=500)http5.push({status:r.status(),url:r.url()})});
 try{
  fx=await pair(request,project);await page.addInitScript(t=>localStorage.setItem('prime_token',t),fx.a.token);await page.goto('/',{waitUntil:'domcontentloaded',timeout:20000});await page.waitForTimeout(900);await dismiss(page);await page.waitForFunction(()=>typeof window.PRIME?.openConnect==='function',{timeout:10000});await page.evaluate(()=>window.PRIME.openConnect());await expect(page.locator('#primeconnect')).toBeVisible();await page.waitForTimeout(900);await audit(page,'chat-list',issues,screens,project);
  const row=page.locator(`[data-pc46-chat="${fx.b.handle}"]`).first();await expect(row).toBeVisible();for(let i=0;i<8;i++){await row.dispatchEvent('click');await page.waitForTimeout(35)}await expect(page.locator('.pc46-chatpage')).toBeVisible();await page.waitForTimeout(1000);await audit(page,'chat-open-fast',issues,screens,project);
  let stats=await page.evaluate(()=>window.PRIME_CHAT_ENGINE_STATS?.()||{});if(Number(stats.messages||0)<90)add(issues,'HIGH','INITIAL_HISTORY_SHORT','Открылось меньше ожидаемых последних сообщений','После входа в большой чат движок должен получить около 100 последних сообщений.',stats);
  const body=page.locator('.pc46-chatbody');for(let i=0;i<14;i++){await body.evaluate(e=>{e.scrollTop=0;e.dispatchEvent(new Event('scroll'))});await page.waitForTimeout(320);stats=await page.evaluate(()=>window.PRIME_CHAT_ENGINE_STATS?.()||{});loaded=Number(stats.messages||0);if(loaded>=530)break}if(loaded<530)add(issues,'HIGH','HISTORY_PAGINATION_INCOMPLETE',`Из 530 сообщений загружено ${loaded}`,'При прокрутке вверх старая история перестаёт догружаться — часть переписки недоступна.',{loaded,expected:530,stats});await audit(page,'history-loaded',issues,screens,project);
  const model=await page.evaluate(()=>{const c=window.PRIME?.state?.connect?.open?.messages||[];return{count:c.length,long:c.some(m=>String(m.body||'').length>3000),deleted:c.some(m=>!!m.deleted_for_all_at),reply:c.some(m=>!!m.reply_to_id),photos:c.filter(m=>m.message_type==='image').length,reactions:c.reduce((n,m)=>n+(m.reactions?.length||0),0)}});if(!model.long)add(issues,'HIGH','LONG_MESSAGE_MISSING','Длинное сообщение потерялось','История не содержит тестовое длинное сообщение после pagination.',model);if(!model.deleted)add(issues,'MEDIUM','DELETED_MESSAGE_MISSING','Удалённое сообщение не представлено','Состояние deleted_for_all не дошло до клиента.',model);if(!model.reply)add(issues,'MEDIUM','REPLY_RELATION_MISSING','Reply потерял связь','reply_to_id не дошёл до полной истории.',model);if(model.photos<30)add(issues,'HIGH','PHOTO_BATCH_INCOMPLETE',`Из 30 фото доступно ${model.photos}`,'Большая серия фотографий загружается не полностью.',model);
  await body.evaluate(e=>{e.scrollTop=e.scrollHeight;e.dispatchEvent(new Event('scroll'))});await page.waitForTimeout(900);const imgs=page.locator('img.pc47-photo');const imgCount=await imgs.count();if(imgCount<1)add(issues,'HIGH','PHOTO_RENDER_EMPTY','Фото есть в модели, но нет в DOM','Медиа-сообщения не отрисовались в видимой области.',{imgCount});else{const bad=await imgs.evaluateAll(xs=>xs.filter(x=>x.complete&&(!x.naturalWidth||!x.naturalHeight)).length);if(bad)add(issues,'HIGH','PHOTO_RENDER_BROKEN',`Не загрузились ${bad} видимых фото`,'В серии фото появились битые изображения.',{bad,imgCount})}await audit(page,'photo-grid',issues,screens,project);
  const input=page.locator('#pc46input');await input.fill('QA LIVE SEND');await page.locator('.pc47-send,.pc46-send').click();await page.waitForTimeout(850);const live=page.locator('.pc47-msg').filter({hasText:'QA LIVE SEND'}).last();if(!await live.isVisible().catch(()=>false))add(issues,'HIGH','SEND_UI_FAILED','Сообщение через composer не появилось','Обычная отправка текста из интерфейса не завершилась отображением сообщения.');else{await touchHold(page,live,700);await page.waitForTimeout(150);if(!await page.locator('#pc47menu').isVisible().catch(()=>false))add(issues,'HIGH','LONG_PRESS_CONTEXT_FAILED','Long‑press не открыл меню сообщения','Удержание сообщения не показывает reply/reaction/edit/delete меню.');else{await audit(page,'long-press-menu',issues,screens,project);const reply=page.locator('#pc47menu [data-pc47-act="reply"]');if(await reply.isVisible().catch(()=>false)){await reply.click();await page.waitForTimeout(150);if(!await page.locator('.pc47-context').isVisible().catch(()=>false))add(issues,'HIGH','REPLY_CONTEXT_FAILED','Reply не активировал composer context','После «Ответить» над composer не появился блок ответа.');else{const close=page.locator('[data-pc47-context-close]');await close.click();await page.waitForTimeout(120);if(await page.locator('.pc47-context').isVisible().catch(()=>false))add(issues,'HIGH','REPLY_CANCEL_FAILED','Крестик не отменяет reply','Контекст ответа остаётся после нажатия закрытия.')}}}}
  await page.setViewportSize({width:info.project.name==='compact-iphone'?375:393,height:430});await input.focus();await page.waitForTimeout(250);await audit(page,'keyboard-short-viewport',issues,screens,project);await page.setViewportSize({width:info.project.name==='compact-iphone'?375:393,height:info.project.name==='compact-iphone'?667:852});
  let abortOnce=true;await page.route('**/functions/v1/prime-chat',async route=>{const req=route.request(),pd=req.postData()||'';if(abortOnce&&req.method()==='POST'&&pd.includes('"action":"send"')){abortOnce=false;simulatedAbort=true;await route.abort('internetdisconnected');setTimeout(()=>{simulatedAbort=false},300);return}await route.continue()});await input.fill('QA NETWORK FAIL');await page.locator('.pc47-send,.pc46-send').click();await page.waitForTimeout(700);if(!await page.locator('.pc47-msg.failed,.pc46-msg.failed').isVisible().catch(()=>false))add(issues,'MEDIUM','SEND_FAILURE_NOT_VISIBLE','Сетевой сбой отправки не показан','При обрыве сети пользователь не видит, что сообщение не отправилось.');await page.unroute('**/functions/v1/prime-chat');
  await input.fill('QA RECOVERY SEND');await page.locator('.pc47-send,.pc46-send').click();await page.waitForTimeout(700);if(!await page.locator('.pc47-msg').filter({hasText:'QA RECOVERY SEND'}).last().isVisible().catch(()=>false))add(issues,'HIGH','SEND_RECOVERY_FAILED','После сетевой ошибки чат не восстановился','Следующее нормальное сообщение не отправляется после одного отказа сети.');
  await audit(page,'after-network-recovery',issues,screens,project);
  const pageRect=await page.locator('.pc46-chatpage').boundingBox();if(pageRect){await page.locator('.pc46-chatpage').dispatchEvent('pointerdown',{pointerId:91,pointerType:'touch',isPrimary:true,clientX:4,clientY:Math.min(300,pageRect.height/2),buttons:1});await page.locator('.pc46-chatpage').dispatchEvent('pointermove',{pointerId:91,pointerType:'touch',isPrimary:true,clientX:Math.min(220,pageRect.width*.65),clientY:Math.min(302,pageRect.height/2+2),buttons:1});await page.locator('.pc46-chatpage').dispatchEvent('pointerup',{pointerId:91,pointerType:'touch',isPrimary:true,clientX:Math.min(260,pageRect.width*.75),clientY:Math.min(302,pageRect.height/2+2),buttons:0});await page.waitForTimeout(450);if(await page.locator('.pc46-chatpage').isVisible().catch(()=>false))add(issues,'MEDIUM','EDGE_SWIPE_BACK_FAILED','Edge‑swipe назад не закрыл чат','Свайп от левого края не возвращает к списку чатов.');}
  if(pageErrors.length)add(issues,'CRITICAL','CONTACT_PAGE_ERROR',`JavaScript exceptions: ${pageErrors.length}`,'В мессенджере возникли необработанные JS-ошибки.',{sample:pageErrors.slice(0,6)});if(http5.length)add(issues,'HIGH','CONTACT_HTTP_5XX',`HTTP 5xx: ${http5.length}`,'Backend PRIME Contact вернул серверную ошибку.',{sample:http5.slice(0,8)});if(requestFailures.length)add(issues,'MEDIUM','CONTACT_REQUEST_FAILURE',`Оборвано запросов: ${requestFailures.length}`,'В обычном сценарии запросы физически не завершились.',{sample:requestFailures.slice(0,8)});
 }catch(e){add(issues,'CRITICAL','CONTACT_AUTOPILOT_FATAL','Contact QA оборвался','Глубокий сценарий не смог дойти до конца.',{error:String(e?.stack||e).slice(0,3000)});await page.screenshot({path:`artifacts/contact-screens/${slug(project)}-fatal.png`}).catch(()=>null)}finally{save(project,{run_id:RUN,project,duration_ms:Date.now()-started,seeded:fx?.seeded?.count||0,loaded_history:loaded,issues,screens,console_errors:consoleErrors,page_errors:pageErrors,request_failures:requestFailures,http_5xx:http5});await cleanup(request,fx)}
 expect(issues.filter(x=>x.severity==='CRITICAL'||x.severity==='HIGH'),'Blocking PRIME Contact bugs; inspect contact artifact').toHaveLength(0);
});
