import { test, expect } from '@playwright/test';
import fs from 'node:fs';

const SB='https://lqnnqsopdqnibbyzoakc.supabase.co',AUTH=`${SB}/functions/v1/prime-auth`,CLEAN=`${SB}/functions/v1/prime-qa-cleanup`,RUN=String(process.env.GITHUB_RUN_ID||Date.now());
const VIEWS=['cardv','checkv','calv','friendsv'];
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,50)||'x';
const add=(a,severity,code,title,meaning,detail={})=>a.push({severity,code,title,meaning,detail});
async function auth(request,project){const s=slug(project).replace(/-/g,'').slice(0,10),q={email:`qa2-main-${RUN}-${s}@prime.invalid`,password:`PrimeMain-${RUN}-${s}-X9!`,handle:`qa2_${String(RUN).slice(-9)}_m_${s}`.slice(0,32),display_name:`QA 2.0 MAIN ${s}`.slice(0,32)};const r=await request.post(AUTH,{data:{action:'signup',...q}}),d=await r.json().catch(()=>({}));if(!r.ok()||!d?.token)throw new Error(`main auth ${r.status()} ${JSON.stringify(d).slice(0,300)}`);return d.token}
async function cleanup(request,t){if(!t)return;await request.post(CLEAN,{headers:{Authorization:`Bearer ${t}`},data:{}}).catch(()=>null)}
async function dismiss(page){const ss=['#releasecontinue','[data-release-onboard-skip]','[data-prime-guide="skip"]','[data-action="onboard-skip"]','#onboard button:has-text("ПРОПУСТИТЬ")','#onboard button:has-text("Пропустить")','button:has-text("ПРОПУСТИТЬ")','button:has-text("Пропустить")'];for(let pass=0;pass<18;pass++){let acted=false;for(const s of ss){const e=page.locator(s).first();if(await e.isVisible().catch(()=>false)){await e.click({force:true,timeout:1200}).catch(()=>null);acted=true;await page.waitForTimeout(80)}}if(!acted)await page.waitForTimeout(120)}}
async function hit(page,sel){return page.locator(sel).first().evaluate(e=>{const r=e.getBoundingClientRect(),x=Math.max(1,Math.min(innerWidth-1,r.left+r.width/2)),y=Math.max(1,Math.min(innerHeight-1,r.top+r.height/2)),t=document.elementFromPoint(x,y);return{rect:{left:r.left,top:r.top,right:r.right,bottom:r.bottom,width:r.width,height:r.height},x,y,hit:t?(t.getAttribute?.('aria-label')||t.textContent||t.id||t.className||t.tagName).toString().trim().replace(/\s+/g,' ').slice(0,100):null,owns:!!(t&&(t===e||e.contains(t)||t.contains(e)))}})}
async function touch(page,sel){const e=page.locator(sel).first();if(!await e.isVisible().catch(()=>false))return{ok:false,reason:'missing'};const h=await hit(page,sel);if(!h.owns)return{ok:false,reason:'covered',...h};await page.touchscreen.tap(h.x,h.y);return{ok:true,...h}}
async function audit(page,label,issues,screens,project){const a=await page.evaluate(()=>{const vis=e=>{if(!e)return false;const c=getComputedStyle(e),r=e.getBoundingClientRect();return c.display!=='none'&&c.visibility!=='hidden'&&+c.opacity>.02&&r.width>0&&r.height>0},gate=document.getElementById('primecallpermissiongate'),gateOn=vis(gate),blocked=[];if(gateOn)for(const e of [...document.querySelectorAll('button,a,[role="button"]')].filter(vis)){if(gate.contains(e))continue;const r=e.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)continue;const x=Math.max(1,Math.min(innerWidth-1,r.left+r.width/2)),y=Math.max(1,Math.min(innerHeight-1,r.top+r.height/2)),t=document.elementFromPoint(x,y);if(t&&gate.contains(t))blocked.push((e.getAttribute('aria-label')||e.textContent||e.id||e.tagName).trim().replace(/\s+/g,' ').slice(0,90))}const nav=document.querySelector('.prime-navigator-more'),nr=nav&&vis(nav)?{children:nav.children.length,hasMoreCopy:!!nav.querySelector('.morecopy'),text:nav.textContent.trim().replace(/\s+/g,' ').slice(0,150)}:null;return{gateOn,blocked,nav:nr,active:[...document.querySelectorAll('#app .view.on')].filter(vis).map(e=>e.id),overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth)}});const p=`artifacts/main-screens/${slug(project)}-${slug(label)}.png`;fs.mkdirSync('artifacts/main-screens',{recursive:true});await page.screenshot({path:p});screens.push({label,screenshot:p,audit:a});if(a.blocked.length)add(issues,'HIGH','CALL_GATE_BLOCKS_UI',`${label}: call permission перекрывает кнопки`,'Плашка разрешения звонков забирает тапы у интерфейса.',{blocked:a.blocked});if(a.nav&&(!a.nav.hasMoreCopy||a.nav.children<3))add(issues,'HIGH','NAVIGATOR_LAYOUT',`${label}: карточка НАВИГАТОР сломана`,'DOM карточки не соответствует нормальной moreitem-разметке.',a.nav);if(a.active.length!==1)add(issues,'HIGH','ACTIVE_VIEW_COUNT',`${label}: active views ${a.active.length}`,'Одновременно активно неправильное число основных экранов.',{active:a.active});if(a.overflow>4)add(issues,'MEDIUM','MAIN_OVERFLOW',`${label}: overflow ${a.overflow}px`,'Основная страница шире viewport.',{overflow:a.overflow});return a}
function save(project,r){fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync(`artifacts/main-${project}.json`,JSON.stringify(r,null,2));const c=r.issues.reduce((a,x)=>(a[x.severity]=(a[x.severity]||0)+1,a),{}),o=[`# PRIME Main Recheck — ${project}`,'',`- Issues: ${r.issues.length} (CRITICAL ${c.CRITICAL||0}, HIGH ${c.HIGH||0}, MEDIUM ${c.MEDIUM||0})`,`- Duration: ${r.duration_ms} ms`,'','## Bugs',''];if(!r.issues.length)o.push('Подтверждённых проблем не найдено.');r.issues.forEach((x,i)=>o.push(`### MAIN-${String(i+1).padStart(3,'0')} · ${x.severity} · ${x.code}`,`**Баг:** ${x.title}`,`**Что это значит:** ${x.meaning}`,`**Детали:** \`${JSON.stringify(x.detail).slice(0,1600)}\``,''));fs.writeFileSync(`artifacts/main-${project}.md`,o.join('\n'))}

test('PRIME main R13.2 recheck',async({page,request},info)=>{test.setTimeout(100000);const start=Date.now(),project=info.project.name,issues=[],screens=[],http401=[],http5=[],pageErrors=[];let token=null;page.on('response',r=>{if(r.status()===401)http401.push(r.url());if(r.status()>=500)http5.push({status:r.status(),url:r.url()})});page.on('pageerror',e=>pageErrors.push(String(e?.message||e).slice(0,900)));try{token=await auth(request,project);await page.addInitScript(t=>localStorage.setItem('prime_token',t),token);await page.goto('/',{waitUntil:'domcontentloaded',timeout:20000});await page.waitForTimeout(1200);await dismiss(page);await expect(page.locator('#app')).toBeVisible();await audit(page,'boot',issues,screens,project);
 for(const id of VIEWS){await dismiss(page);const sel=`#primeXBar [data-x-view="${id}"]`;const r=await touch(page,sel);if(!r.ok){add(issues,'HIGH','NAV_TOUCH_BLOCKED',`${id}: touch не проходит`,'Физическая точка тапа принадлежит другому слою или кнопка отсутствует.',r);continue}await page.waitForTimeout(130);if(!await page.locator(`#${id}.on`).isVisible().catch(()=>false))add(issues,'HIGH','NAV_TOUCH_WRONG_TARGET',`${id}: touch не открыл экран`,'После реального touch ожидаемый раздел не стал активным.');await audit(page,id,issues,screens,project)}
 if(project==='compact-iphone'){await dismiss(page);await touch(page,'#primeXBar [data-x-view="checkv"]');await page.waitForTimeout(140);const tell=page.locator('#checkv .nerve-actions button, #checkv .nerve-actions [role="button"]').first();if(await tell.isVisible().catch(()=>false)){const h=await hit(page,'#checkv .nerve-actions button, #checkv .nerve-actions [role="button"]');if(!h.owns)add(issues,'HIGH','TELL_PRIME_COVERED','TELL PRIME перекрыт нижней навигацией','Кнопка видна, но её центр принимает другой слой.',h)}}
 await dismiss(page);const more=page.locator('#moremenu');if(await more.isVisible().catch(()=>false)){await more.click();await page.waitForTimeout(180);await audit(page,'more',issues,screens,project);await page.locator('#sheetclose').click().catch(()=>page.locator('#sheetback').click({position:{x:2,y:2}}).catch(()=>null));await page.waitForTimeout(180)}
 for(let i=0;i<20;i++){await dismiss(page);const id=VIEWS[i%4],sel=`#primeXBar [data-x-view="${id}"]`,r=await touch(page,sel);if(!r.ok){add(issues,'HIGH','STRESS_TOUCH_BLOCKED',`Stress ${i+1}: ${id} touch заблокирован`,'Во время быстрых реальных tap координата навигации попала не в кнопку.',{iteration:i,...r});break}await page.waitForTimeout(85);if(!await page.locator(`#${id}.on`).isVisible().catch(()=>false)){add(issues,'HIGH','STRESS_TOUCH_WRONG_TARGET',`Stress ${i+1}: ${id} не открылся`,'Touch прошёл по самой кнопке, но приложение не переключило раздел.',{iteration:i});break}}
 await audit(page,'post-stress',issues,screens,project);const profile401=http401.filter(u=>u.includes('prime_profiles'));if(profile401.length)add(issues,'HIGH','PUBLIC_PROFILE_401',`Public profiles всё ещё дают 401 (${profile401.length})`,'Запрос публичного рейтинга не авторизуется.',{sample:profile401.slice(0,5)});if(http5.length)add(issues,'HIGH','MAIN_HTTP_5XX',`HTTP 5xx: ${http5.length}`,'Production API вернул серверную ошибку.',{sample:http5.slice(0,8)});if(pageErrors.length)add(issues,'HIGH','MAIN_PAGE_ERRORS',`JS exceptions: ${pageErrors.length}`,'В основном PRIME есть необработанные ошибки JavaScript.',{sample:pageErrors.slice(0,8)})}catch(e){add(issues,'CRITICAL','MAIN_RECHECK_FATAL','Main recheck оборвался','Проверка не смогла завершить сценарий.',{error:String(e?.stack||e).slice(0,2600)})}finally{save(project,{run_id:RUN,project,duration_ms:Date.now()-start,issues,screens,http_401:http401,http_5xx:http5,page_errors:pageErrors});await cleanup(request,token)}expect(issues.filter(x=>x.severity==='CRITICAL'||x.severity==='HIGH'),'Blocking main PRIME bugs').toHaveLength(0)});
